//////////////////////////////////////////////////////////////////////
// C++ source file generated by SpecC V2.2.1
// Design: CannyA6
// File:   CannyA6.cc
// Time:   Sun May 21 10:19:02 2017
//////////////////////////////////////////////////////////////////////

// Note: User-defined include files are inlined in this file.

// Note: System-defined include files are inlined in this file.

#include "CannyA6.h"


unsigned int _IDcnt = 0;
// variable definitions //////////////////////////////////////////////

unsigned int __PRF_globalCounter[212];

// channel class definitions /////////////////////////////////////////

c_img_queue::c_img_queue(const unsigned long int (&size))
    : _specc::channel(), size(size),
    buffer(0),
    n(0ul),
    p(0ul),
    wr(0ul),
    ws(0ul)
{   
}

c_img_queue::~c_img_queue(void)
{   
}

#line 53 "Canny.sc"
void c_img_queue::cleanup(void) { if ( !n) { free(buffer); buffer = 0;
    }
}

#line 53 "Canny.sc"
void c_img_queue::receive(unsigned char (*d)[4110080]) { while( !n) { wr++ ; _specc::wait(event(&r), ((void*)0)); wr-- ;
    }

#line 53 "Canny.sc"
    if (n <= p) { { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<4110080;_scc_index_0++) ( *d)[_scc_index_0] = (buffer[p - n])[_scc_index_0]; }
    }
    else 

#line 53 "Canny.sc"
    {    { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<4110080;_scc_index_0++) ( *d)[_scc_index_0] = (buffer[p + size - n])[_scc_index_0]; }
    }

#line 53 "Canny.sc"
    n-- ; if (ws) { _specc::notify(event(&s), ((void*)0));
    }

#line 53 "Canny.sc"
    cleanup();
}

#line 53 "Canny.sc"
void c_img_queue::send(unsigned char d[4110080]) { while(n >= size) { ws++ ; _specc::wait(event(&s), ((void*)0)); ws-- ;
    }

#line 53 "Canny.sc"
    setup(); { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<4110080;_scc_index_0++) (buffer[p])[_scc_index_0] = (d)[_scc_index_0]; } p++ ; if (p >= size) { p = 0;
    }

#line 53 "Canny.sc"
    n++ ; if (wr) { _specc::notify(event(&r), ((void*)0));
    }
}

#line 53 "Canny.sc"
void c_img_queue::setup(void) { if ( !buffer) { unsigned char dummy[4110080]; unsigned long int i; if ( !(buffer = (unsigned char (*)[4110080])malloc(sizeof(unsigned char [4110080]) * size))) { perror("c_typed_queue"); abort();
	}

#line 53 "Canny.sc"
	for(i = 0; i < size; i++ ) { memcpy( &buffer[i],  &dummy, sizeof(unsigned char [4110080]));
	}
    }
}

#line 86 "CannyA6.cc"
c_simg_queue::c_simg_queue(const unsigned long int (&size))
    : _specc::channel(), size(size),
    buffer(0),
    n(0ul),
    p(0ul),
    wr(0ul),
    ws(0ul)
{   
}

c_simg_queue::~c_simg_queue(void)
{   
}

#line 60 "Canny.sc"
void c_simg_queue::cleanup(void) { if ( !n) { free(buffer); buffer = 0;
    }
}

#line 60 "Canny.sc"
void c_simg_queue::receive(short int (*d)[4110080]) { while( !n) { wr++ ; _specc::wait(event(&r), ((void*)0)); wr-- ;
    }

#line 60 "Canny.sc"
    if (n <= p) { { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<4110080;_scc_index_0++) ( *d)[_scc_index_0] = (buffer[p - n])[_scc_index_0]; }
    }
    else 

#line 60 "Canny.sc"
    {    { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<4110080;_scc_index_0++) ( *d)[_scc_index_0] = (buffer[p + size - n])[_scc_index_0]; }
    }

#line 60 "Canny.sc"
    n-- ; if (ws) { _specc::notify(event(&s), ((void*)0));
    }

#line 60 "Canny.sc"
    cleanup();
}

#line 60 "Canny.sc"
void c_simg_queue::send(short int d[4110080]) { while(n >= size) { ws++ ; _specc::wait(event(&s), ((void*)0)); ws-- ;
    }

#line 60 "Canny.sc"
    setup(); { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<4110080;_scc_index_0++) (buffer[p])[_scc_index_0] = (d)[_scc_index_0]; } p++ ; if (p >= size) { p = 0;
    }

#line 60 "Canny.sc"
    n++ ; if (wr) { _specc::notify(event(&r), ((void*)0));
    }
}

#line 60 "Canny.sc"
void c_simg_queue::setup(void) { if ( !buffer) { short int dummy[4110080]; unsigned long int i; if ( !(buffer = (short int (*)[4110080])malloc(sizeof(short int [4110080]) * size))) { perror("c_typed_queue"); abort();
	}

#line 60 "Canny.sc"
	for(i = 0; i < size; i++ ) { memcpy( &buffer[i],  &dummy, sizeof(short int [4110080]));
	}
    }
}

#line 150 "CannyA6.cc"
c_float1_queue::c_float1_queue(const unsigned long int (&size))
    : _specc::channel(), size(size),
    buffer(0),
    n(0ul),
    p(0ul),
    wr(0ul),
    ws(0ul)
{   
}

c_float1_queue::~c_float1_queue(void)
{   
}

#line 67 "Canny.sc"
void c_float1_queue::cleanup(void) { if ( !n) { free(buffer); buffer = 0;
    }
}

#line 67 "Canny.sc"
void c_float1_queue::receive(float (*d)[4110080]) { while( !n) { wr++ ; _specc::wait(event(&r), ((void*)0)); wr-- ;
    }

#line 67 "Canny.sc"
    if (n <= p) { { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<4110080;_scc_index_0++) ( *d)[_scc_index_0] = (buffer[p - n])[_scc_index_0]; }
    }
    else 

#line 67 "Canny.sc"
    {    { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<4110080;_scc_index_0++) ( *d)[_scc_index_0] = (buffer[p + size - n])[_scc_index_0]; }
    }

#line 67 "Canny.sc"
    n-- ; if (ws) { _specc::notify(event(&s), ((void*)0));
    }

#line 67 "Canny.sc"
    cleanup();
}

#line 67 "Canny.sc"
void c_float1_queue::send(float d[4110080]) { while(n >= size) { ws++ ; _specc::wait(event(&s), ((void*)0)); ws-- ;
    }

#line 67 "Canny.sc"
    setup(); { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<4110080;_scc_index_0++) (buffer[p])[_scc_index_0] = (d)[_scc_index_0]; } p++ ; if (p >= size) { p = 0;
    }

#line 67 "Canny.sc"
    n++ ; if (wr) { _specc::notify(event(&r), ((void*)0));
    }
}

#line 67 "Canny.sc"
void c_float1_queue::setup(void) { if ( !buffer) { float dummy[4110080]; unsigned long int i; if ( !(buffer = (float (*)[4110080])malloc(sizeof(float [4110080]) * size))) { perror("c_typed_queue"); abort();
	}

#line 67 "Canny.sc"
	for(i = 0; i < size; i++ ) { memcpy( &buffer[i],  &dummy, sizeof(float [4110080]));
	}
    }
}

#line 214 "CannyA6.cc"
c_float2_queue::c_float2_queue(const unsigned long int (&size))
    : _specc::channel(), size(size),
    buffer(0),
    n(0ul),
    p(0ul),
    wr(0ul),
    ws(0ul)
{   
}

c_float2_queue::~c_float2_queue(void)
{   
}

#line 73 "Canny.sc"
void c_float2_queue::cleanup(void) { if ( !n) { free(buffer); buffer = 0;
    }
}

#line 73 "Canny.sc"
void c_float2_queue::receive(float (*d)[21]) { while( !n) { wr++ ; _specc::wait(event(&r), ((void*)0)); wr-- ;
    }

#line 73 "Canny.sc"
    if (n <= p) { { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<21;_scc_index_0++) ( *d)[_scc_index_0] = (buffer[p - n])[_scc_index_0]; }
    }
    else 

#line 73 "Canny.sc"
    {    { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<21;_scc_index_0++) ( *d)[_scc_index_0] = (buffer[p + size - n])[_scc_index_0]; }
    }

#line 73 "Canny.sc"
    n-- ; if (ws) { _specc::notify(event(&s), ((void*)0));
    }

#line 73 "Canny.sc"
    cleanup();
}

#line 73 "Canny.sc"
void c_float2_queue::send(float d[21]) { while(n >= size) { ws++ ; _specc::wait(event(&s), ((void*)0)); ws-- ;
    }

#line 73 "Canny.sc"
    setup(); { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<21;_scc_index_0++) (buffer[p])[_scc_index_0] = (d)[_scc_index_0]; } p++ ; if (p >= size) { p = 0;
    }

#line 73 "Canny.sc"
    n++ ; if (wr) { _specc::notify(event(&r), ((void*)0));
    }
}

#line 73 "Canny.sc"
void c_float2_queue::setup(void) { if ( !buffer) { float dummy[21]; unsigned long int i; if ( !(buffer = (float (*)[21])malloc(sizeof(float [21]) * size))) { perror("c_typed_queue"); abort();
	}

#line 73 "Canny.sc"
	for(i = 0; i < size; i++ ) { memcpy( &buffer[i],  &dummy, sizeof(float [21]));
	}
    }
}

// behavior class definitions ////////////////////////////////////////

#line 280 "CannyA6.cc"
Stimulus::Stimulus(unsigned int _idcnt, i_img_sender (&ImgOut))
    : _specc::behavior(_idcnt), ImgOut(ImgOut)
{   
}

Stimulus::~Stimulus(void)
{   
}

void Stimulus::main(void)

#line 144 "Canny.sc"
{   
    int i = 0; int n = 0;
    char infilename[40];

#line 297 "CannyA6.cc"
    __PRF_globalCounter[49u]++ ;

#line 148 "Canny.sc"
    for(i = 0; i < 20; i++ )
    {   

#line 304 "CannyA6.cc"
	__PRF_globalCounter[50u]++ ;

#line 150 "Canny.sc"
	n = i % 20;
	sprintf(infilename, "video/EngPlaza%03d.pgm", n + 1);

#line 311 "CannyA6.cc"
	__PRF_globalCounter[51u]++ ;

#line 156 "Canny.sc"
	if (0)

#line 317 "CannyA6.cc"
	{   
	    __PRF_globalCounter[52u]++ ;

#line 156 "Canny.sc"
	    printf("Reading the image %s.\n", infilename);
	}

#line 325 "CannyA6.cc"
	__PRF_globalCounter[53u]++ ;

#line 157 "Canny.sc"
	if (read_pgm_image(infilename, Image, 1520, 2704) == 0) {

#line 331 "CannyA6.cc"
	    __PRF_globalCounter[54u]++ ;

#line 158 "Canny.sc"
	    fprintf(stderr, "Error reading the input image, %s.\n", infilename);
	    exit(1);
	}

#line 339 "CannyA6.cc"
	__PRF_globalCounter[55u]++ ;

#line 161 "Canny.sc"
	ImgOut.send(Image);
    }
}

#line 347 "CannyA6.cc"
int Stimulus::read_pgm_image(

#line 90 "Canny.sc"
    const char *infilename, unsigned char *image, int rows, int cols)
{   
    struct _IO_FILE *fp;
    char buf[71];
    int c; int r;

#line 357 "CannyA6.cc"
    __PRF_globalCounter[56u]++ ;

#line 100 "Canny.sc"
    if (infilename == ((void *)0))

#line 363 "CannyA6.cc"
    {   
	__PRF_globalCounter[57u]++ ;

#line 100 "Canny.sc"
	fp = stdin;
    }
    else 

#line 101 "Canny.sc"
    {   

#line 375 "CannyA6.cc"
	__PRF_globalCounter[58u]++ ;

#line 102 "Canny.sc"
	if ((fp = fopen(infilename, "r")) == ((void *)0)) {

#line 381 "CannyA6.cc"
	    __PRF_globalCounter[59u]++ ;

#line 103 "Canny.sc"
	    fprintf(stderr, "Error reading the file %s in read_pgm_image().\n", 
		infilename);
	    return (0);
	}
    }

#line 391 "CannyA6.cc"
    __PRF_globalCounter[60u]++ ;

#line 113 "Canny.sc"
    fgets(buf, 70, fp);

#line 397 "CannyA6.cc"
    __PRF_globalCounter[61u]++ ;

#line 114 "Canny.sc"
    if (strncmp(buf, "P5", 2) != 0) {

#line 403 "CannyA6.cc"
	__PRF_globalCounter[62u]++ ;

#line 115 "Canny.sc"
	fprintf(stderr, "The file %s is not in PGM format in ", infilename);
	fprintf(stderr, "read_pgm_image().\n");

#line 410 "CannyA6.cc"
	__PRF_globalCounter[63u]++ ;

#line 117 "Canny.sc"
	if (fp != stdin)

#line 416 "CannyA6.cc"
	{   
	    __PRF_globalCounter[64u]++ ;

#line 117 "Canny.sc"
	    fclose(fp);
	}

#line 424 "CannyA6.cc"
	__PRF_globalCounter[65u]++ ;

#line 118 "Canny.sc"
	return (0);
    }

#line 431 "CannyA6.cc"
    __PRF_globalCounter[66u]++ ;

#line 120 "Canny.sc"
    do  {

#line 437 "CannyA6.cc"
	__PRF_globalCounter[67u]++ ;

#line 120 "Canny.sc"
	fgets(buf, 70, fp);
    }
    while(

#line 120 "Canny.sc"
	buf[0] == '#');

#line 448 "CannyA6.cc"
    __PRF_globalCounter[68u]++ ;

#line 121 "Canny.sc"
    __isoc99_sscanf(buf, "%d %d",  &c,  &r);

#line 454 "CannyA6.cc"
    __PRF_globalCounter[69u]++ ;

#line 122 "Canny.sc"
    if (c != cols || r != rows) {

#line 460 "CannyA6.cc"
	__PRF_globalCounter[70u]++ ;

#line 123 "Canny.sc"
	fprintf(stderr, "The file %s is not a %d by %d image in ", infilename, cols, rows);
	fprintf(stderr, "read_pgm_image().\n");

#line 467 "CannyA6.cc"
	__PRF_globalCounter[71u]++ ;

#line 125 "Canny.sc"
	if (fp != stdin)

#line 473 "CannyA6.cc"
	{   
	    __PRF_globalCounter[72u]++ ;

#line 125 "Canny.sc"
	    fclose(fp);
	}

#line 481 "CannyA6.cc"
	__PRF_globalCounter[73u]++ ;

#line 126 "Canny.sc"
	return (0);
    }

#line 488 "CannyA6.cc"
    __PRF_globalCounter[74u]++ ;

#line 128 "Canny.sc"
    do  {

#line 494 "CannyA6.cc"
	__PRF_globalCounter[75u]++ ;

#line 128 "Canny.sc"
	fgets(buf, 70, fp);
    }
    while(

#line 128 "Canny.sc"
	buf[0] == '#');

#line 505 "CannyA6.cc"
    __PRF_globalCounter[76u]++ ;

#line 133 "Canny.sc"
    if ((unsigned int)rows != fread(image, cols, rows, fp)) {

#line 511 "CannyA6.cc"
	__PRF_globalCounter[77u]++ ;

#line 134 "Canny.sc"
	fprintf(stderr, "Error reading the image data in read_pgm_image().\n");

#line 517 "CannyA6.cc"
	__PRF_globalCounter[78u]++ ;

#line 135 "Canny.sc"
	if (fp != stdin)

#line 523 "CannyA6.cc"
	{   
	    __PRF_globalCounter[79u]++ ;

#line 135 "Canny.sc"
	    fclose(fp);
	}

#line 531 "CannyA6.cc"
	__PRF_globalCounter[80u]++ ;

#line 136 "Canny.sc"
	return (0);
    }

#line 538 "CannyA6.cc"
    __PRF_globalCounter[81u]++ ;

#line 139 "Canny.sc"
    if (fp != stdin)

#line 544 "CannyA6.cc"
    {   
	__PRF_globalCounter[82u]++ ;

#line 139 "Canny.sc"
	fclose(fp);
    }

#line 552 "CannyA6.cc"
    __PRF_globalCounter[83u]++ ;

#line 140 "Canny.sc"
    return (1);
}

#line 559 "CannyA6.cc"
Monitor::Monitor(unsigned int _idcnt, i_img_receiver (&ImgIn))
    : _specc::behavior(_idcnt), ImgIn(ImgIn)
{   
}

Monitor::~Monitor(void)
{   
}

void Monitor::main(void)

#line 216 "Canny.sc"
{   
    char outfilename[128];
    int i; int n;

#line 576 "CannyA6.cc"
    __PRF_globalCounter[22u]++ ;

#line 220 "Canny.sc"
    for(i = 0; i < 20; i++ )
    {   

#line 583 "CannyA6.cc"
	__PRF_globalCounter[23u]++ ;

#line 222 "Canny.sc"
	ImgIn.receive( &EdgeImage);




	n = i % 20;
	sprintf(outfilename, "EngPlaza%03d_edges.pgm", n + 1);

#line 595 "CannyA6.cc"
	__PRF_globalCounter[24u]++ ;

#line 229 "Canny.sc"
	if (0)

#line 601 "CannyA6.cc"
	{   
	    __PRF_globalCounter[25u]++ ;

#line 229 "Canny.sc"
	    printf("Writing the edge image in the file %s.\n", outfilename);
	}

#line 609 "CannyA6.cc"
	__PRF_globalCounter[26u]++ ;

#line 230 "Canny.sc"
	if (write_pgm_image(outfilename, EdgeImage, 1520, 2704, "", 255) == 0) {

#line 615 "CannyA6.cc"
	    __PRF_globalCounter[27u]++ ;

#line 231 "Canny.sc"
	    fprintf(stderr, "Error writing the edge image, %s.\n", outfilename);
	    exit(1);
	}
    }

#line 624 "CannyA6.cc"
    __PRF_globalCounter[28u]++ ;

#line 235 "Canny.sc"
    if (0)

#line 630 "CannyA6.cc"
    {   
	__PRF_globalCounter[29u]++ ;

#line 235 "Canny.sc"
	printf("Monitor exits simulation.\n");
    }

#line 638 "CannyA6.cc"
    __PRF_globalCounter[30u]++ ;

#line 236 "Canny.sc"
    sim_exit(0);
}

#line 645 "CannyA6.cc"
int Monitor::write_pgm_image(

#line 176 "Canny.sc"
    const char *outfilename, unsigned char *image, int rows, 
    int cols, const char *comment, int maxval)
{   
    struct _IO_FILE *fp;

#line 654 "CannyA6.cc"
    __PRF_globalCounter[31u]++ ;

#line 185 "Canny.sc"
    if (outfilename == ((void *)0))

#line 660 "CannyA6.cc"
    {   
	__PRF_globalCounter[32u]++ ;

#line 185 "Canny.sc"
	fp = stdout;
    }
    else 

#line 186 "Canny.sc"
    {   

#line 672 "CannyA6.cc"
	__PRF_globalCounter[33u]++ ;

#line 187 "Canny.sc"
	if ((fp = fopen(outfilename, "w")) == ((void *)0)) {

#line 678 "CannyA6.cc"
	    __PRF_globalCounter[34u]++ ;

#line 188 "Canny.sc"
	    fprintf(stderr, "Error writing the file %s in write_pgm_image().\n", 
		outfilename);
	    return (0);
	}
    }

#line 688 "CannyA6.cc"
    __PRF_globalCounter[35u]++ ;

#line 197 "Canny.sc"
    fprintf(fp, "P5\n%d %d\n", cols, rows);

#line 694 "CannyA6.cc"
    __PRF_globalCounter[36u]++ ;

#line 198 "Canny.sc"
    if (comment != ((void *)0))

#line 700 "CannyA6.cc"
    {   
	__PRF_globalCounter[37u]++ ;

#line 199 "Canny.sc"
	if (strlen(comment) <= 70)

#line 707 "CannyA6.cc"
	{   
	    __PRF_globalCounter[38u]++ ;

#line 199 "Canny.sc"
	    fprintf(fp, "# %s\n", comment);
	}
    }

#line 716 "CannyA6.cc"
    __PRF_globalCounter[39u]++ ;

#line 200 "Canny.sc"
    fprintf(fp, "%d\n", maxval);

#line 722 "CannyA6.cc"
    __PRF_globalCounter[40u]++ ;

#line 205 "Canny.sc"
    if ((unsigned int)rows != fwrite(image, cols, rows, fp)) {

#line 728 "CannyA6.cc"
	__PRF_globalCounter[41u]++ ;

#line 206 "Canny.sc"
	fprintf(stderr, "Error writing the image data in write_pgm_image().\n");

#line 734 "CannyA6.cc"
	__PRF_globalCounter[42u]++ ;

#line 207 "Canny.sc"
	if (fp != stdout)

#line 740 "CannyA6.cc"
	{   
	    __PRF_globalCounter[43u]++ ;

#line 207 "Canny.sc"
	    fclose(fp);
	}

#line 748 "CannyA6.cc"
	__PRF_globalCounter[44u]++ ;

#line 208 "Canny.sc"
	return (0);
    }

#line 755 "CannyA6.cc"
    __PRF_globalCounter[45u]++ ;

#line 211 "Canny.sc"
    if (fp != stdout)

#line 761 "CannyA6.cc"
    {   
	__PRF_globalCounter[46u]++ ;

#line 211 "Canny.sc"
	fclose(fp);
    }

#line 769 "CannyA6.cc"
    __PRF_globalCounter[47u]++ ;

#line 212 "Canny.sc"
    return (1);
}

#line 776 "CannyA6.cc"
DataIn::DataIn(unsigned int _idcnt, i_img_receiver (&ImgIn), i_img_sender (&ImgOut))
    : _specc::behavior(_idcnt), ImgIn(ImgIn), ImgOut(ImgOut)
{   
}

DataIn::~DataIn(void)
{   
}

void DataIn::main()

#line 245 "Canny.sc"
{   

#line 791 "CannyA6.cc"
    __PRF_globalCounter[16u]++ ;

#line 246 "Canny.sc"
    while(1)
    {   

#line 798 "CannyA6.cc"
	__PRF_globalCounter[17u]++ ;

#line 248 "Canny.sc"
	ImgIn.receive( &Image);
	ImgOut.send(Image);
    }
}

#line 807 "CannyA6.cc"
DataOut::DataOut(unsigned int _idcnt, i_img_receiver (&ImgIn), i_img_sender (&ImgOut))
    : _specc::behavior(_idcnt), ImgIn(ImgIn), ImgOut(ImgOut)
{   
}

DataOut::~DataOut(void)
{   
}

void DataOut::main()

#line 259 "Canny.sc"
{   

#line 822 "CannyA6.cc"
    __PRF_globalCounter[18u]++ ;

#line 260 "Canny.sc"
    while(1)
    {   

#line 829 "CannyA6.cc"
	__PRF_globalCounter[19u]++ ;

#line 262 "Canny.sc"
	ImgIn.receive( &Image);
	ImgOut.send(Image);
    }
}

#line 838 "CannyA6.cc"
receiveImage::receiveImage(unsigned int _idcnt, i_img_receiver (&ImgIn), unsigned char (&ImgOut)[4110080])
    : _specc::behavior(_idcnt), ImgIn(ImgIn), ImgOut(ImgOut)
{   
}

receiveImage::~receiveImage(void)
{   
}

void receiveImage::main()

#line 273 "Canny.sc"
{   

#line 853 "CannyA6.cc"
    __PRF_globalCounter[211u]++ ;

#line 275 "Canny.sc"
    ImgIn.receive( &Image);
    { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<4110080;_scc_index_0++) (ImgOut)[_scc_index_0] = (Image)[_scc_index_0]; }
}

#line 861 "CannyA6.cc"
make_gaussian_kernel::make_gaussian_kernel(unsigned int _idcnt, float (&kernelout)[21])
    : _specc::behavior(_idcnt), kernelout(kernelout),
    sigma(6.000000e-01f),
    windowsize(21)
{   
}

make_gaussian_kernel::~make_gaussian_kernel(void)
{   
}

void make_gaussian_kernel::main()

#line 315 "Canny.sc"
{   

#line 878 "CannyA6.cc"
    __PRF_globalCounter[166u]++ ;

#line 317 "Canny.sc"
    if (0)

#line 884 "CannyA6.cc"
    {   
	__PRF_globalCounter[167u]++ ;

#line 317 "Canny.sc"
	printf("   Computing the gaussian smoothing kernel.\n");
    }

#line 892 "CannyA6.cc"
    __PRF_globalCounter[168u]++ ;

#line 318 "Canny.sc"
    make_gaussian_kernel1(sigma, kernel,  &windowsize);


    { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<21;_scc_index_0++) (kernelout)[_scc_index_0] = (kernel)[_scc_index_0]; }
}

#line 902 "CannyA6.cc"
void make_gaussian_kernel::make_gaussian_kernel1(

#line 288 "Canny.sc"
    float sigma, float *kernel, int *windowsize)
{   
    int center; int i;
    float fx; float sum = 0.000000e+00f; float x;

#line 911 "CannyA6.cc"
    __PRF_globalCounter[169u]++ ;

#line 293 "Canny.sc"
     *windowsize = 1 + 2 * ceil(2.500000000000000e+00 * sigma);
    center = ( *windowsize) / 2;

#line 918 "CannyA6.cc"
    __PRF_globalCounter[170u]++ ;

#line 296 "Canny.sc"
    if (0)

#line 924 "CannyA6.cc"
    {   
	__PRF_globalCounter[171u]++ ;

#line 296 "Canny.sc"
	printf("      The kernel has %d elements.\n",  *windowsize);
    }

#line 932 "CannyA6.cc"
    __PRF_globalCounter[172u]++ ;

#line 298 "Canny.sc"
    for(i = 0; i < ( *windowsize); i++ ) {

#line 938 "CannyA6.cc"
	__PRF_globalCounter[173u]++ ;

#line 299 "Canny.sc"
	x = (float)(i - center);
	fx = pow(2.718280000000000e+00,  -5.000000000000000e-01 * x * x / (sigma * sigma)) / (sigma * sqrt(6.283185300000000e+00));
	kernel[i] = fx;
	sum += fx;
    }

#line 948 "CannyA6.cc"
    __PRF_globalCounter[174u]++ ;

#line 305 "Canny.sc"
    for(i = 0; i < ( *windowsize); i++ )

#line 954 "CannyA6.cc"
    {   
	__PRF_globalCounter[175u]++ ;

#line 305 "Canny.sc"
	kernel[i] /= sum;
    }

#line 962 "CannyA6.cc"
    __PRF_globalCounter[176u]++ ;

#line 307 "Canny.sc"
    if (0) {

#line 968 "CannyA6.cc"
	__PRF_globalCounter[177u]++ ;

#line 308 "Canny.sc"
	printf("The filter coefficients are:\n");

#line 974 "CannyA6.cc"
	__PRF_globalCounter[178u]++ ;

#line 309 "Canny.sc"
	for(i = 0; i < ( *windowsize); i++ )

#line 980 "CannyA6.cc"
	{   
	    __PRF_globalCounter[179u]++ ;

#line 310 "Canny.sc"
	    printf("kernel[%d] = %f\n", i, kernel[i]);
	}
    }
}

#line 990 "CannyA6.cc"
blurX::blurX(unsigned int _idcnt, float (&kernelin)[21], unsigned char (&ImgIn)[4110080], float (&tempimout)[4110080])
    : _specc::behavior(_idcnt), kernelin(kernelin), ImgIn(ImgIn), tempimout(tempimout),
    cols(2704),
    rows(1520),
    windowsize(21)
{   
}

blurX::~blurX(void)
{   
}

void blurX::main()

#line 339 "Canny.sc"
{   

#line 1008 "CannyA6.cc"
    __PRF_globalCounter[123u]++ ;

#line 341 "Canny.sc"
    { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<21;_scc_index_0++) (kernel)[_scc_index_0] = (kernelin)[_scc_index_0]; }
    { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<4110080;_scc_index_0++) (image)[_scc_index_0] = (ImgIn)[_scc_index_0]; }
    center = windowsize / 2;

#line 1016 "CannyA6.cc"
    __PRF_globalCounter[124u]++ ;

#line 347 "Canny.sc"
    if (0)

#line 1022 "CannyA6.cc"
    {   
	__PRF_globalCounter[125u]++ ;

#line 347 "Canny.sc"
	printf("   Bluring the image in the X-direction.\n");
    }

#line 1030 "CannyA6.cc"
    __PRF_globalCounter[126u]++ ;

#line 348 "Canny.sc"
    for(r = 0; r < rows; r++ ) {

#line 1036 "CannyA6.cc"
	__PRF_globalCounter[127u]++ ;

#line 349 "Canny.sc"
	for(c = 0; c < cols; c++ ) {

#line 1042 "CannyA6.cc"
	    __PRF_globalCounter[128u]++ ;

#line 350 "Canny.sc"
	    dot = 0.000000000000000e+00;
	    sum = 0.000000000000000e+00;

#line 1049 "CannyA6.cc"
	    __PRF_globalCounter[129u]++ ;

#line 352 "Canny.sc"
	    for(cc = ( -center); cc <= center; cc++ ) {

#line 1055 "CannyA6.cc"
		__PRF_globalCounter[130u]++ ;

#line 353 "Canny.sc"
		if (((c + cc) >= 0) && ((c + cc) < cols)) {

#line 1061 "CannyA6.cc"
		    __PRF_globalCounter[131u]++ ;

#line 354 "Canny.sc"
		    dot += (float)image[r * cols + (c + cc)] * kernel[center + cc];
		    sum += kernel[center + cc];
		}
	    }

#line 1070 "CannyA6.cc"
	    __PRF_globalCounter[132u]++ ;

#line 358 "Canny.sc"
	    tempim[r * cols + c] = dot / sum;
	}
    }

#line 1078 "CannyA6.cc"
    __PRF_globalCounter[133u]++ ;

#line 362 "Canny.sc"
    { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<4110080;_scc_index_0++) (tempimout)[_scc_index_0] = (tempim)[_scc_index_0]; }
}

#line 1085 "CannyA6.cc"
blurY::blurY(unsigned int _idcnt, float (&kernelin)[21], float (&tempimin)[4110080], short int (&smoothedimout)[4110080])
    : _specc::behavior(_idcnt), kernelin(kernelin), tempimin(tempimin), smoothedimout(smoothedimout),
    cols(2704),
    rows(1520),
    windowsize(21)
{   
}

blurY::~blurY(void)
{   
}

void blurY::main()

#line 378 "Canny.sc"
{   

#line 1103 "CannyA6.cc"
    __PRF_globalCounter[134u]++ ;

#line 379 "Canny.sc"
    { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<21;_scc_index_0++) (kernel)[_scc_index_0] = (kernelin)[_scc_index_0]; }
    { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<4110080;_scc_index_0++) (tempim)[_scc_index_0] = (tempimin)[_scc_index_0]; }
    center = windowsize / 2;

#line 1111 "CannyA6.cc"
    __PRF_globalCounter[135u]++ ;

#line 385 "Canny.sc"
    if (0)

#line 1117 "CannyA6.cc"
    {   
	__PRF_globalCounter[136u]++ ;

#line 385 "Canny.sc"
	printf("   Bluring the image in the Y-direction.\n");
    }

#line 1125 "CannyA6.cc"
    __PRF_globalCounter[137u]++ ;

#line 386 "Canny.sc"
    for(c = 0; c < cols; c++ ) {

#line 1131 "CannyA6.cc"
	__PRF_globalCounter[138u]++ ;

#line 387 "Canny.sc"
	for(r = 0; r < rows; r++ ) {

#line 1137 "CannyA6.cc"
	    __PRF_globalCounter[139u]++ ;

#line 388 "Canny.sc"
	    sum = 0.000000000000000e+00;
	    dot = 0.000000000000000e+00;

#line 1144 "CannyA6.cc"
	    __PRF_globalCounter[140u]++ ;

#line 390 "Canny.sc"
	    for(rr = ( -center); rr <= center; rr++ ) {

#line 1150 "CannyA6.cc"
		__PRF_globalCounter[141u]++ ;

#line 391 "Canny.sc"
		if (((r + rr) >= 0) && ((r + rr) < rows)) {

#line 1156 "CannyA6.cc"
		    __PRF_globalCounter[142u]++ ;

#line 392 "Canny.sc"
		    dot += tempim[(r + rr) * cols + c] * kernel[center + rr];
		    sum += kernel[center + rr];
		}
	    }

#line 1165 "CannyA6.cc"
	    __PRF_globalCounter[143u]++ ;

#line 396 "Canny.sc"
	    smoothedim[r * cols + c] = (short int)(dot * 9.000000000000000e+01 / sum + 5.000000000000000e-01);
	}
    }

#line 1173 "CannyA6.cc"
    __PRF_globalCounter[144u]++ ;

#line 400 "Canny.sc"
    { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<4110080;_scc_index_0++) (smoothedimout)[_scc_index_0] = (smoothedim)[_scc_index_0]; }
}

#line 1180 "CannyA6.cc"
gaussian_smooth::gaussian_smooth(unsigned int _idcnt, i_img_receiver (&ImgIn), short int (&sImgOut)[4110080])
    : _specc::behavior(_idcnt), ImgIn(ImgIn), sImgOut(sImgOut),
    bx(_IDcnt, kernel, Image, tempim),
    by(_IDcnt, kernel, tempim, sImgOut),
    mgk(_IDcnt, kernel),
    ri(_IDcnt, ImgIn, Image)
{   
}

gaussian_smooth::~gaussian_smooth(void)
{   
}

void gaussian_smooth::main()

#line 422 "Canny.sc"
{   

#line 1199 "CannyA6.cc"
    __PRF_globalCounter[160u]++ ;

#line 424 "Canny.sc"
    ri.main();
    mgk.main();
    bx.main();
    by.main();
}

#line 1209 "CannyA6.cc"
derivative_x_y::derivative_x_y(unsigned int _idcnt, short int (&sImgIn)[4110080], short int (&xImgOut)[4110080], short int (&yImgOut)[4110080])
    : _specc::behavior(_idcnt), sImgIn(sImgIn), xImgOut(xImgOut), yImgOut(yImgOut),
    cols(2704),
    rows(1520)
{   
}

derivative_x_y::~derivative_x_y(void)
{   
}

void derivative_x_y::derivative_x_y1(

#line 439 "Canny.sc"
    short int *smoothedim, int rows, int cols, 
    short int *delta_x, short int *delta_y)
{   
    int c; int pos; int r;

#line 1229 "CannyA6.cc"
    __PRF_globalCounter[145u]++ ;

#line 448 "Canny.sc"
    if (0)

#line 1235 "CannyA6.cc"
    {   
	__PRF_globalCounter[146u]++ ;

#line 448 "Canny.sc"
	printf("   Computing the X-direction derivative.\n");
    }

#line 1243 "CannyA6.cc"
    __PRF_globalCounter[147u]++ ;

#line 449 "Canny.sc"
    for(r = 0; r < rows; r++ ) {

#line 1249 "CannyA6.cc"
	__PRF_globalCounter[148u]++ ;

#line 450 "Canny.sc"
	pos = r * cols;
	delta_x[pos] = smoothedim[pos + 1] - smoothedim[pos];
	pos++ ;

#line 1257 "CannyA6.cc"
	__PRF_globalCounter[149u]++ ;

#line 453 "Canny.sc"
	for(c = 1; c < (cols - 1); c++  , pos++ ) {

#line 1263 "CannyA6.cc"
	    __PRF_globalCounter[150u]++ ;

#line 454 "Canny.sc"
	    delta_x[pos] = smoothedim[pos + 1] - smoothedim[pos - 1];
	}

#line 1270 "CannyA6.cc"
	__PRF_globalCounter[151u]++ ;

#line 456 "Canny.sc"
	delta_x[pos] = smoothedim[pos] - smoothedim[pos - 1];
    }

#line 1277 "CannyA6.cc"
    __PRF_globalCounter[152u]++ ;

#line 463 "Canny.sc"
    if (0)

#line 1283 "CannyA6.cc"
    {   
	__PRF_globalCounter[153u]++ ;

#line 463 "Canny.sc"
	printf("   Computing the Y-direction derivative.\n");
    }

#line 1291 "CannyA6.cc"
    __PRF_globalCounter[154u]++ ;

#line 464 "Canny.sc"
    for(c = 0; c < cols; c++ ) {

#line 1297 "CannyA6.cc"
	__PRF_globalCounter[155u]++ ;

#line 465 "Canny.sc"
	pos = c;
	delta_y[pos] = smoothedim[pos + cols] - smoothedim[pos];
	pos += cols;

#line 1305 "CannyA6.cc"
	__PRF_globalCounter[156u]++ ;

#line 468 "Canny.sc"
	for(r = 1; r < (rows - 1); r++  , pos += cols) {

#line 1311 "CannyA6.cc"
	    __PRF_globalCounter[157u]++ ;

#line 469 "Canny.sc"
	    delta_y[pos] = smoothedim[pos + cols] - smoothedim[pos - cols];
	}

#line 1318 "CannyA6.cc"
	__PRF_globalCounter[158u]++ ;

#line 471 "Canny.sc"
	delta_y[pos] = smoothedim[pos] - smoothedim[pos - cols];
    }
}

#line 1326 "CannyA6.cc"
void derivative_x_y::main()

#line 475 "Canny.sc"
{   

#line 1332 "CannyA6.cc"
    __PRF_globalCounter[159u]++ ;

#line 478 "Canny.sc"
    { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<4110080;_scc_index_0++) (smoothedim)[_scc_index_0] = (sImgIn)[_scc_index_0]; }

    derivative_x_y1(smoothedim, rows, cols, delta_x, delta_y);

    { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<4110080;_scc_index_0++) (xImgOut)[_scc_index_0] = (delta_x)[_scc_index_0]; }
    { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<4110080;_scc_index_0++) (yImgOut)[_scc_index_0] = (delta_y)[_scc_index_0]; }
}

#line 1344 "CannyA6.cc"
magnitude_x_y::magnitude_x_y(unsigned int _idcnt, short int (&DxIn)[4110080], short int (&DyIn)[4110080], short int (&magOut)[4110080])
    : _specc::behavior(_idcnt), DxIn(DxIn), DyIn(DyIn), magOut(magOut),
    cols(2704),
    rows(1520)
{   
}

magnitude_x_y::~magnitude_x_y(void)
{   
}

void magnitude_x_y::main()

#line 499 "Canny.sc"
{   

#line 1361 "CannyA6.cc"
    __PRF_globalCounter[161u]++ ;

#line 500 "Canny.sc"
    { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<4110080;_scc_index_0++) (delta_x)[_scc_index_0] = (DxIn)[_scc_index_0]; }
    { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<4110080;_scc_index_0++) (delta_y)[_scc_index_0] = (DyIn)[_scc_index_0]; }

#line 1368 "CannyA6.cc"
    __PRF_globalCounter[162u]++ ;

#line 503 "Canny.sc"
    for(r = 0 , pos = 0; r < rows; r++ ) {

#line 1374 "CannyA6.cc"
	__PRF_globalCounter[163u]++ ;

#line 504 "Canny.sc"
	for(c = 0; c < cols; c++  , pos++ ) {

#line 1380 "CannyA6.cc"
	    __PRF_globalCounter[164u]++ ;

#line 505 "Canny.sc"
	    sq1 = (int)delta_x[pos] * (int)delta_x[pos];
	    sq2 = (int)delta_y[pos] * (int)delta_y[pos];
	    magnitude[pos] = (short int)(5.000000000000000e-01 + sqrt((float)sq1 + (float)sq2));
	}
    }

#line 1390 "CannyA6.cc"
    __PRF_globalCounter[165u]++ ;

#line 511 "Canny.sc"
    { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<4110080;_scc_index_0++) (magOut)[_scc_index_0] = (magnitude)[_scc_index_0]; }
}

#line 1397 "CannyA6.cc"
non_max_supp::non_max_supp(unsigned int _idcnt, short int (&magIn)[4110080], short int (&DxIn)[4110080], short int (&DyIn)[4110080], unsigned char (&nmsOut)[4110080])
    : _specc::behavior(_idcnt), magIn(magIn), DxIn(DxIn), DyIn(DyIn), nmsOut(nmsOut),
    cols(2704),
    rows(1520)
{   
}

non_max_supp::~non_max_supp(void)
{   
}

void non_max_supp::main()

#line 732 "Canny.sc"
{   

#line 1414 "CannyA6.cc"
    __PRF_globalCounter[180u]++ ;

#line 734 "Canny.sc"
    { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<4110080;_scc_index_0++) (delta_x)[_scc_index_0] = (DxIn)[_scc_index_0]; }
    { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<4110080;_scc_index_0++) (delta_y)[_scc_index_0] = (DyIn)[_scc_index_0]; }
    { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<4110080;_scc_index_0++) (magnitude)[_scc_index_0] = (magIn)[_scc_index_0]; }

    non_max_supp1(magnitude, delta_x, delta_y, rows, cols, nms);
    { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<4110080;_scc_index_0++) (nmsOut)[_scc_index_0] = (nms)[_scc_index_0]; }
}

#line 1426 "CannyA6.cc"
void non_max_supp::non_max_supp1(

#line 534 "Canny.sc"
    short int *mag, short int *gradx, short int *grady, int nrows, int ncols, 
    unsigned char *result)
{   
    int colcount; int count; int rowcount;
    short int *magptr; short int *magrowptr;
    short int *gxptr; short int *gxrowptr;
    short int *gyptr; short int *gyrowptr; short int z1; short int z2;
    short int gx; short int gy; short int m00;
    float mag1; float mag2; float xperp; float yperp;
    unsigned char *resultptr; unsigned char *resultrowptr;

#line 1441 "CannyA6.cc"
    __PRF_globalCounter[181u]++ ;

#line 548 "Canny.sc"
    for(count = 0 , resultrowptr = result , resultptr = result + ncols * (nrows - 1); 
	count < ncols; resultptr++  , resultrowptr++  , count++ ) {

#line 1448 "CannyA6.cc"
	__PRF_globalCounter[182u]++ ;

#line 550 "Canny.sc"
	 *resultrowptr =  *resultptr = (unsigned char)0;
    }

#line 1455 "CannyA6.cc"
    __PRF_globalCounter[183u]++ ;

#line 553 "Canny.sc"
    for(count = 0 , resultptr = result , resultrowptr = result + ncols - 1; 
	count < nrows; count++  , resultptr += ncols , resultrowptr += ncols) {

#line 1462 "CannyA6.cc"
	__PRF_globalCounter[184u]++ ;

#line 555 "Canny.sc"
	 *resultptr =  *resultrowptr = (unsigned char)0;
    }

#line 1469 "CannyA6.cc"
    __PRF_globalCounter[185u]++ ;

#line 561 "Canny.sc"
    for(rowcount = 1 , magrowptr = mag + ncols + 1 , gxrowptr = gradx + ncols + 1 , 
	gyrowptr = grady + ncols + 1 , resultrowptr = result + ncols + 1; 
	rowcount <= nrows - 2; 
	rowcount++  , magrowptr += ncols , gyrowptr += ncols , gxrowptr += ncols , 
	resultrowptr += ncols) {

#line 1479 "CannyA6.cc"
	__PRF_globalCounter[186u]++ ;

#line 566 "Canny.sc"
	for(colcount = 1 , magptr = magrowptr , gxptr = gxrowptr , gyptr = gyrowptr , 
	    resultptr = resultrowptr; colcount <= ncols - 2; 
	    colcount++  , magptr++  , gxptr++  , gyptr++  , resultptr++ ) {

#line 1487 "CannyA6.cc"
	    __PRF_globalCounter[187u]++ ;

#line 569 "Canny.sc"
	    m00 =  *magptr;

#line 1493 "CannyA6.cc"
	    __PRF_globalCounter[188u]++ ;

#line 570 "Canny.sc"
	    if (m00 == 0) {

#line 1499 "CannyA6.cc"
		__PRF_globalCounter[189u]++ ;

#line 571 "Canny.sc"
		 *resultptr = (unsigned char)255;
	    }
	    else  {

#line 1507 "CannyA6.cc"
		__PRF_globalCounter[190u]++ ;

#line 574 "Canny.sc"
		xperp =  -(gx =  *gxptr) / ((float)m00);
		yperp = (gy =  *gyptr) / ((float)m00);
	    }

#line 1515 "CannyA6.cc"
	    __PRF_globalCounter[191u]++ ;

#line 578 "Canny.sc"
	    if (gx >= 0) {

#line 1521 "CannyA6.cc"
		__PRF_globalCounter[192u]++ ;

#line 579 "Canny.sc"
		if (gy >= 0) {

#line 1527 "CannyA6.cc"
		    __PRF_globalCounter[193u]++ ;

#line 580 "Canny.sc"
		    if (gx >= gy)
		    {   

#line 1534 "CannyA6.cc"
			__PRF_globalCounter[194u]++ ;

#line 584 "Canny.sc"
			z1 =  *(magptr - 1);
			z2 =  *(magptr - ncols - 1);

			mag1 = (m00 - z1) * xperp + (z2 - z1) * yperp;


			z1 =  *(magptr + 1);
			z2 =  *(magptr + ncols + 1);

			mag2 = (m00 - z1) * xperp + (z2 - z1) * yperp;
		    }
		    else 
		    {   

#line 1552 "CannyA6.cc"
			__PRF_globalCounter[195u]++ ;

#line 599 "Canny.sc"
			z1 =  *(magptr - ncols);
			z2 =  *(magptr - ncols - 1);

			mag1 = (z1 - z2) * xperp + (z1 - m00) * yperp;


			z1 =  *(magptr + ncols);
			z2 =  *(magptr + ncols + 1);

			mag2 = (z1 - z2) * xperp + (z1 - m00) * yperp;
		    }
		}
		else 
		{   

#line 1571 "CannyA6.cc"
		    __PRF_globalCounter[196u]++ ;

#line 613 "Canny.sc"
		    if (gx >=  -gy)
		    {   

#line 1578 "CannyA6.cc"
			__PRF_globalCounter[197u]++ ;

#line 617 "Canny.sc"
			z1 =  *(magptr - 1);
			z2 =  *(magptr + ncols - 1);

			mag1 = (m00 - z1) * xperp + (z1 - z2) * yperp;


			z1 =  *(magptr + 1);
			z2 =  *(magptr - ncols + 1);

			mag2 = (m00 - z1) * xperp + (z1 - z2) * yperp;
		    }
		    else 
		    {   

#line 1596 "CannyA6.cc"
			__PRF_globalCounter[198u]++ ;

#line 632 "Canny.sc"
			z1 =  *(magptr + ncols);
			z2 =  *(magptr + ncols - 1);

			mag1 = (z1 - z2) * xperp + (m00 - z1) * yperp;


			z1 =  *(magptr - ncols);
			z2 =  *(magptr - ncols + 1);

			mag2 = (z1 - z2) * xperp + (m00 - z1) * yperp;
		    }
		}
	    }
	    else 
	    {   

#line 1616 "CannyA6.cc"
		__PRF_globalCounter[199u]++ ;

#line 647 "Canny.sc"
		if ((gy =  *gyptr) >= 0)
		{   

#line 1623 "CannyA6.cc"
		    __PRF_globalCounter[200u]++ ;

#line 649 "Canny.sc"
		    if ( -gx >= gy)
		    {   

#line 1630 "CannyA6.cc"
			__PRF_globalCounter[201u]++ ;

#line 653 "Canny.sc"
			z1 =  *(magptr + 1);
			z2 =  *(magptr - ncols + 1);

			mag1 = (z1 - m00) * xperp + (z2 - z1) * yperp;


			z1 =  *(magptr - 1);
			z2 =  *(magptr + ncols - 1);

			mag2 = (z1 - m00) * xperp + (z2 - z1) * yperp;
		    }
		    else 
		    {   

#line 1648 "CannyA6.cc"
			__PRF_globalCounter[202u]++ ;

#line 668 "Canny.sc"
			z1 =  *(magptr - ncols);
			z2 =  *(magptr - ncols + 1);

			mag1 = (z2 - z1) * xperp + (z1 - m00) * yperp;


			z1 =  *(magptr + ncols);
			z2 =  *(magptr + ncols - 1);

			mag2 = (z2 - z1) * xperp + (z1 - m00) * yperp;
		    }
		}
		else 
		{   

#line 1667 "CannyA6.cc"
		    __PRF_globalCounter[203u]++ ;

#line 682 "Canny.sc"
		    if ( -gx >  -gy)
		    {   

#line 1674 "CannyA6.cc"
			__PRF_globalCounter[204u]++ ;

#line 686 "Canny.sc"
			z1 =  *(magptr + 1);
			z2 =  *(magptr + ncols + 1);

			mag1 = (z1 - m00) * xperp + (z1 - z2) * yperp;


			z1 =  *(magptr - 1);
			z2 =  *(magptr - ncols - 1);

			mag2 = (z1 - m00) * xperp + (z1 - z2) * yperp;
		    }
		    else 
		    {   

#line 1692 "CannyA6.cc"
			__PRF_globalCounter[205u]++ ;

#line 701 "Canny.sc"
			z1 =  *(magptr + ncols);
			z2 =  *(magptr + ncols + 1);

			mag1 = (z2 - z1) * xperp + (m00 - z1) * yperp;


			z1 =  *(magptr - ncols);
			z2 =  *(magptr - ncols - 1);

			mag2 = (z2 - z1) * xperp + (m00 - z1) * yperp;
		    }
		}
	    }

#line 1710 "CannyA6.cc"
	    __PRF_globalCounter[206u]++ ;

#line 717 "Canny.sc"
	    if ((mag1 > 0.000000000000000e+00) || (mag2 > 0.000000000000000e+00))
	    {   

#line 1717 "CannyA6.cc"
		__PRF_globalCounter[207u]++ ;

#line 719 "Canny.sc"
		 *resultptr = (unsigned char)255;
	    }
	    else 
	    {   

#line 1726 "CannyA6.cc"
		__PRF_globalCounter[208u]++ ;

#line 723 "Canny.sc"
		if (mag2 == 0.000000000000000e+00)

#line 1732 "CannyA6.cc"
		{   
		    __PRF_globalCounter[209u]++ ;

#line 724 "Canny.sc"
		     *resultptr = (unsigned char)255;
		}
		else 

#line 1741 "CannyA6.cc"
		{   
		    __PRF_globalCounter[210u]++ ;

#line 726 "Canny.sc"
		     *resultptr = (unsigned char)128;
		}
	    }
	}
    }
}

#line 1753 "CannyA6.cc"
apply_hysteresis::apply_hysteresis(unsigned int _idcnt, short int (&magIn)[4110080], unsigned char (&nmsIn)[4110080], i_img_sender (&ImgOut))
    : _specc::behavior(_idcnt), magIn(magIn), nmsIn(nmsIn), ImgOut(ImgOut),
    cols(2704),
    rows(1520),
    thigh(8.000000e-01f),
    tlow(3.000000e-01f)
{   
}

apply_hysteresis::~apply_hysteresis(void)
{   
}

void apply_hysteresis::apply_hysteresis1(

#line 790 "Canny.sc"
    short int *mag, unsigned char *nms, int rows, int cols, 
    float tlow, float thigh, unsigned char *edge)
{   
    int c; int highcount; int highthreshold; int hist[32768]; int lowthreshold; int numedges; int pos; int r;
    short int maximum_mag;

#line 1776 "CannyA6.cc"
    __PRF_globalCounter[84u]++ ;

#line 803 "Canny.sc"
    for(r = 0 , pos = 0; r < rows; r++ ) {

#line 1782 "CannyA6.cc"
	__PRF_globalCounter[85u]++ ;

#line 804 "Canny.sc"
	for(c = 0; c < cols; c++  , pos++ ) {

#line 1788 "CannyA6.cc"
	    __PRF_globalCounter[86u]++ ;

#line 805 "Canny.sc"
	    if (nms[pos] == 128)

#line 1794 "CannyA6.cc"
	    {   
		__PRF_globalCounter[87u]++ ;

#line 805 "Canny.sc"
		edge[pos] = 128;
	    }
	    else 

#line 1803 "CannyA6.cc"
	    {   
		__PRF_globalCounter[88u]++ ;

#line 806 "Canny.sc"
		edge[pos] = 255;
	    }
	}
    }

#line 1813 "CannyA6.cc"
    __PRF_globalCounter[89u]++ ;

#line 810 "Canny.sc"
    for(r = 0 , pos = 0; r < rows; r++  , pos += cols) {

#line 1819 "CannyA6.cc"
	__PRF_globalCounter[90u]++ ;

#line 811 "Canny.sc"
	edge[pos] = 255;
	edge[pos + cols - 1] = 255;
    }

#line 1827 "CannyA6.cc"
    __PRF_globalCounter[91u]++ ;

#line 814 "Canny.sc"
    pos = (rows - 1) * cols;

#line 1833 "CannyA6.cc"
    __PRF_globalCounter[92u]++ ;

#line 815 "Canny.sc"
    for(c = 0; c < cols; c++  , pos++ ) {

#line 1839 "CannyA6.cc"
	__PRF_globalCounter[93u]++ ;

#line 816 "Canny.sc"
	edge[c] = 255;
	edge[pos] = 255;
    }

#line 1847 "CannyA6.cc"
    __PRF_globalCounter[94u]++ ;

#line 824 "Canny.sc"
    for(r = 0; r < 32768; r++ )

#line 1853 "CannyA6.cc"
    {   
	__PRF_globalCounter[95u]++ ;

#line 824 "Canny.sc"
	hist[r] = 0;
    }

#line 1861 "CannyA6.cc"
    __PRF_globalCounter[96u]++ ;

#line 825 "Canny.sc"
    for(r = 0 , pos = 0; r < rows; r++ ) {

#line 1867 "CannyA6.cc"
	__PRF_globalCounter[97u]++ ;

#line 826 "Canny.sc"
	for(c = 0; c < cols; c++  , pos++ ) {

#line 1873 "CannyA6.cc"
	    __PRF_globalCounter[98u]++ ;

#line 827 "Canny.sc"
	    if (edge[pos] == 128)

#line 1879 "CannyA6.cc"
	    {   
		__PRF_globalCounter[99u]++ ;

#line 827 "Canny.sc"
		hist[mag[pos]]++ ;
	    }
	}
    }

#line 1889 "CannyA6.cc"
    __PRF_globalCounter[100u]++ ;

#line 834 "Canny.sc"
    for(r = 1 , numedges = 0; r < 32768; r++ ) {

#line 1895 "CannyA6.cc"
	__PRF_globalCounter[101u]++ ;

#line 835 "Canny.sc"
	if (hist[r] != 0)

#line 1901 "CannyA6.cc"
	{   
	    __PRF_globalCounter[102u]++ ;

#line 835 "Canny.sc"
	    maximum_mag = r;
	}

#line 1909 "CannyA6.cc"
	__PRF_globalCounter[103u]++ ;

#line 836 "Canny.sc"
	numedges += hist[r];
    }

#line 1916 "CannyA6.cc"
    __PRF_globalCounter[104u]++ ;

#line 839 "Canny.sc"
    highcount = (int)(numedges * thigh + 5.000000000000000e-01);

#line 851 "Canny.sc"
    r = 1;
    numedges = hist[1];

#line 1926 "CannyA6.cc"
    __PRF_globalCounter[105u]++ ;

#line 853 "Canny.sc"
    while((r < (maximum_mag - 1)) && (numedges < highcount)) {

#line 1932 "CannyA6.cc"
	__PRF_globalCounter[106u]++ ;

#line 854 "Canny.sc"
	r++ ;
	numedges += hist[r];
    }

#line 1940 "CannyA6.cc"
    __PRF_globalCounter[107u]++ ;

#line 857 "Canny.sc"
    highthreshold = r;
    lowthreshold = (int)(highthreshold * tlow + 5.000000000000000e-01);

#line 1947 "CannyA6.cc"
    __PRF_globalCounter[108u]++ ;

#line 860 "Canny.sc"
    if (0) {

#line 1953 "CannyA6.cc"
	__PRF_globalCounter[109u]++ ;

#line 861 "Canny.sc"
	printf("The input low and high fractions of %f and %f computed to\n", 
	    tlow, thigh);
	printf("magnitude of the gradient threshold values of: %d %d\n", 
	    lowthreshold, highthreshold);
    }

#line 1963 "CannyA6.cc"
    __PRF_globalCounter[110u]++ ;

#line 871 "Canny.sc"
    for(r = 0 , pos = 0; r < rows; r++ ) {

#line 1969 "CannyA6.cc"
	__PRF_globalCounter[111u]++ ;

#line 872 "Canny.sc"
	for(c = 0; c < cols; c++  , pos++ ) {

#line 1975 "CannyA6.cc"
	    __PRF_globalCounter[112u]++ ;

#line 873 "Canny.sc"
	    if ((edge[pos] == 128) && (mag[pos] >= highthreshold)) {

#line 1981 "CannyA6.cc"
		__PRF_globalCounter[113u]++ ;

#line 874 "Canny.sc"
		edge[pos] = 0;
		follow_edges((edge + pos), (mag + pos), lowthreshold, cols);
	    }
	}
    }

#line 1991 "CannyA6.cc"
    __PRF_globalCounter[114u]++ ;

#line 883 "Canny.sc"
    for(r = 0 , pos = 0; r < rows; r++ ) {

#line 1997 "CannyA6.cc"
	__PRF_globalCounter[115u]++ ;

#line 884 "Canny.sc"
	for(c = 0; c < cols; c++  , pos++ )

#line 2003 "CannyA6.cc"
	{   
	    __PRF_globalCounter[116u]++ ;

#line 884 "Canny.sc"
	    if (edge[pos] != 0)

#line 2010 "CannyA6.cc"
	    {   
		__PRF_globalCounter[117u]++ ;

#line 884 "Canny.sc"
		edge[pos] = 255;
	    }
	}
    }
}

#line 2021 "CannyA6.cc"
void apply_hysteresis::follow_edges(

#line 762 "Canny.sc"
    unsigned char *edgemapptr, short int *edgemagptr, short int lowval, 
    int cols)
{   
    short int *tempmagptr;
    unsigned char *tempmapptr;
    int i;
    int x[8] = { 1,1,0,-1,-1,-1,0,1 };
    int y[8] = { 0,1,1,1,0,-1,-1,-1 };

#line 2034 "CannyA6.cc"
    __PRF_globalCounter[118u]++ ;

#line 771 "Canny.sc"
    for(i = 0; i < 8; i++ ) {

#line 2040 "CannyA6.cc"
	__PRF_globalCounter[119u]++ ;

#line 772 "Canny.sc"
	tempmapptr = edgemapptr - y[i] * cols + x[i];
	tempmagptr = edgemagptr - y[i] * cols + x[i];

#line 2047 "CannyA6.cc"
	__PRF_globalCounter[120u]++ ;

#line 775 "Canny.sc"
	if (( *tempmapptr == 128) && ( *tempmagptr > lowval)) {

#line 2053 "CannyA6.cc"
	    __PRF_globalCounter[121u]++ ;

#line 776 "Canny.sc"
	     *tempmapptr = (unsigned char)0;
	    follow_edges(tempmapptr, tempmagptr, lowval, cols);
	}
    }
}

#line 2063 "CannyA6.cc"
void apply_hysteresis::main()

#line 888 "Canny.sc"
{   

#line 2069 "CannyA6.cc"
    __PRF_globalCounter[122u]++ ;

#line 891 "Canny.sc"
    { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<4110080;_scc_index_0++) (magnitude)[_scc_index_0] = (magIn)[_scc_index_0]; }
    { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<4110080;_scc_index_0++) (nms)[_scc_index_0] = (nmsIn)[_scc_index_0]; }

    apply_hysteresis1(magnitude, nms, rows, cols, tlow, thigh, edge);

    ImgOut.send(edge);
}

#line 2081 "CannyA6.cc"
DUT::DUT(unsigned int _idcnt, i_img_receiver (&ImgIn), i_img_sender (&ImgOut))
    : _specc::behavior(_idcnt), ImgIn(ImgIn), ImgOut(ImgOut),
    ahy(_IDcnt, mag, nmsq, ImgOut),
    dxy(_IDcnt, sml, dx, dy),
    gs(_IDcnt, ImgIn, sml),
    magxy(_IDcnt, dx, dy, mag),
    nms(_IDcnt, mag, dx, dy, nmsq)
{   
}

DUT::~DUT(void)
{   
}

void DUT::main()

#line 913 "Canny.sc"
{   

#line 2101 "CannyA6.cc"
    __PRF_globalCounter[0u]++ ;

#line 915 "Canny.sc"
    while(1) {

#line 2107 "CannyA6.cc"
	__PRF_globalCounter[1u]++ ;

#line 920 "Canny.sc"
	if (0)

#line 2113 "CannyA6.cc"
	{   
	    __PRF_globalCounter[2u]++ ;

#line 920 "Canny.sc"
	    printf("Smoothing the image using a gaussian kernel.\n");
	}

#line 2121 "CannyA6.cc"
	__PRF_globalCounter[3u]++ ;

#line 921 "Canny.sc"
	gs.main();

#line 2127 "CannyA6.cc"
	__PRF_globalCounter[4u]++ ;

#line 926 "Canny.sc"
	if (0)

#line 2133 "CannyA6.cc"
	{   
	    __PRF_globalCounter[5u]++ ;

#line 926 "Canny.sc"
	    printf("Computing the X and Y first derivatives.\n");
	}

#line 2141 "CannyA6.cc"
	__PRF_globalCounter[6u]++ ;

#line 927 "Canny.sc"
	dxy.main();

#line 2147 "CannyA6.cc"
	__PRF_globalCounter[7u]++ ;

#line 932 "Canny.sc"
	if (0)

#line 2153 "CannyA6.cc"
	{   
	    __PRF_globalCounter[8u]++ ;

#line 932 "Canny.sc"
	    printf("Computing the magnitude of the gradient.\n");
	}

#line 2161 "CannyA6.cc"
	__PRF_globalCounter[9u]++ ;

#line 933 "Canny.sc"
	magxy.main();

#line 2167 "CannyA6.cc"
	__PRF_globalCounter[10u]++ ;

#line 938 "Canny.sc"
	if (0)

#line 2173 "CannyA6.cc"
	{   
	    __PRF_globalCounter[11u]++ ;

#line 938 "Canny.sc"
	    printf("Doing the non-maximal suppression.\n");
	}

#line 2181 "CannyA6.cc"
	__PRF_globalCounter[12u]++ ;

#line 939 "Canny.sc"
	nms.main();

#line 2187 "CannyA6.cc"
	__PRF_globalCounter[13u]++ ;

#line 944 "Canny.sc"
	if (0)

#line 2193 "CannyA6.cc"
	{   
	    __PRF_globalCounter[14u]++ ;

#line 944 "Canny.sc"
	    printf("Doing hysteresis thresholding.\n");
	}

#line 2201 "CannyA6.cc"
	__PRF_globalCounter[15u]++ ;

#line 945 "Canny.sc"
	ahy.main();
    }
}

#line 2209 "CannyA6.cc"
Platform::Platform(unsigned int _idcnt, i_img_receiver (&ImgIn), i_img_sender (&ImgOut))
    : _specc::behavior(_idcnt), ImgIn(ImgIn), ImgOut(ImgOut),
    _scc_const_port_0(2ul),
    _scc_const_port_1(2ul),
    canny(++_IDcnt, q1, q2),
    din(++_IDcnt, ImgIn, q1),
    dout(++_IDcnt, q2, ImgOut),
    q1(_scc_const_port_0),
    q2(_scc_const_port_1)
{   
}

Platform::~Platform(void)
{   
}

void Platform::main()

#line 958 "Canny.sc"
{   
    { _specc::fork _scc_fork_0(&din), _scc_fork_1(&canny), _scc_fork_2(&dout); _specc::par(
	    &_scc_fork_0, 
	    &_scc_fork_1, 
	    &_scc_fork_2, ((_specc::fork*)0));
    }
}

#line 2237 "CannyA6.cc"
Main::Main(unsigned int _idcnt)
    : _specc::class_type(_idcnt),
    _scc_const_port_0(2ul),
    _scc_const_port_1(2ul),
    monitor(_IDcnt, q2),
    platform(_IDcnt, q1, q2),
    q1(_scc_const_port_0),
    q2(_scc_const_port_1),
    stimulus(_IDcnt, q1)
{   
}

Main::~Main(void)
{   
}

int Main::main(void)

#line 976 "Canny.sc"
{   

#line 2259 "CannyA6.cc"
    __PRF_startProfiler("CannyA6.bb_counter.prf", "CannyA6.fn_counter.prf", 
	__PRF_globalCounter, 212u);

#line 977 "Canny.sc"
    { _specc::fork _scc_fork_0(&stimulus), _scc_fork_1(&platform), _scc_fork_2(&monitor); _specc::par(
	    &_scc_fork_0, 
	    &_scc_fork_1, 
	    &_scc_fork_2, ((_specc::fork*)0));
    }

#line 2270 "CannyA6.cc"
    __PRF_globalCounter[21u]++ ;

#line 982 "Canny.sc"
    return 0;
}

#line 2277 "CannyA6.cc"
Main _scc_main(_IDcnt);

int main(void)
{   
    int _scc_main_return;
    
    _specc::start();
    _scc_main_return = _scc_main.main();
    _specc::end();
    return(_scc_main_return);
}

void _scc_bit4_err_handle(
    const _bit4& bit4vec)
{   
    char temp_bits[1024], *p;
    p=bit2str(2,&temp_bits[1023], bit4vec);
    _specc::abort(
	"ERROR:\t Casting a bit4 vector failed \n"
	"Bit4 vector contains X/Z values %s\n"
	"Simulation aborted.\n", p);
	
}

//////////////////////////////////////////////////////////////////////
// End of file CannyA6.cc
//////////////////////////////////////////////////////////////////////
