//////////////////////////////////////////////////////////////////////
// C++ header file generated by SpecC V2.2.1
// Design: ProdCons
// File:   ProdCons.h
// Time:   Wed Apr 12 18:57:51 2017
//////////////////////////////////////////////////////////////////////

// Note: User-defined include files are inlined in this file.

// Note: System-defined include files are inlined in this file.

#include <specc.h>

// named user-defined type declarations //////////////////////////////

struct __pthread_internal_list;
struct timeval;

#line 170 "/usr/include/libio.h"
struct _IO_jump_t;

#line 23 "ProdCons.h"
struct _IO_marker;
struct _IO_FILE;

#line 344 "/usr/include/libio.h"
struct _IO_FILE_plus;

#line 30 "ProdCons.h"
struct random_data;
struct drand48_data;
struct timespec;

// named enumerator type definitions /////////////////////////////////

#line 206 "/usr/include/libio.h"
enum __codecvt_result {

    __codecvt_ok=0,
    __codecvt_partial=1,
    __codecvt_error=2,
    __codecvt_noconv=3
};

// struct/union type definitions /////////////////////////////////////

#line 54 "/opt/sce/inc/bits/pthreadtypes.h"
typedef union {
    char __size[56];
    long int __align; }
    pthread_attr_t;



struct __pthread_internal_list {

    struct __pthread_internal_list *__prev;
    struct __pthread_internal_list *__next;
};

#line 77 "/opt/sce/inc/bits/pthreadtypes.h"
typedef union {

#line 101 "/opt/sce/inc/bits/pthreadtypes.h"
    struct __pthread_mutex_s { int __lock; unsigned int __count; int __owner; unsigned int __nusers; int __kind; int __spins; struct __pthread_internal_list __list; } __data;
    char __size[40];
    long int __align; }
    pthread_mutex_t;


typedef union {
    char __size[4];
    int __align; }
    pthread_mutexattr_t;

#line 116 "/opt/sce/inc/bits/pthreadtypes.h"
typedef union {

#line 133 "/opt/sce/inc/bits/pthreadtypes.h"
    struct { int __lock; unsigned int __futex; int __total_seq1; int __total_seq2; int __wakeup_seq1; int __wakeup_seq2; int __woken_seq1; int __woken_seq2; void *__mutex; unsigned int __nwaiters; unsigned int __broadcast_seq; } __data;
    char __size[48];




    void *__align1;
    long int __align2; }
    pthread_cond_t;


typedef union {
    char __size[4];
    int __align; }
    pthread_condattr_t;

#line 162 "/opt/sce/inc/bits/pthreadtypes.h"
typedef union {

#line 179 "/opt/sce/inc/bits/pthreadtypes.h"
    struct { int __lock; unsigned int __nr_readers; unsigned int __readers_wakeup; unsigned int __writer_wakeup; unsigned int __nr_readers_queued; unsigned int __nr_writers_queued; int __writer; int __shared; unsigned long int __pad1; unsigned long int __pad2; unsigned int __flags; } __data;

#line 198 "/opt/sce/inc/bits/pthreadtypes.h"
    char __size[56];
    long int __align; }
    pthread_rwlock_t;


typedef union {
    char __size[8];
    long int __align; }
    pthread_rwlockattr_t;

#line 218 "/opt/sce/inc/bits/pthreadtypes.h"
typedef union {
    char __size[32];
    long int __align; }
    pthread_barrier_t;


typedef union {
    char __size[4];
    int __align; }
    pthread_barrierattr_t;

#line 84 "/usr/include/wchar.h"
typedef struct {
    int __count;

#line 94 "/usr/include/wchar.h"
    union { unsigned int __wch; char __wchb[4]; } __value; }
    __mbstate_t;

#line 23 "/usr/include/_G_config.h"
typedef struct {
    long int __pos;
    __mbstate_t __state; }
    _G_fpos_t;

typedef struct {
    long int __pos;
    __mbstate_t __state; }
    _G_fpos64_t;

#line 30 "/usr/include/bits/sigset.h"
typedef struct {
    unsigned long int __val[16]; }
    __sigset_t;

#line 75 "/usr/include/bits/time.h"
struct timeval {

    long int tv_sec;
    long int tv_usec;
};

#line 144 "/usr/include/bits/types.h"
typedef struct { int __val[2]; } __fsid_t;

#line 186 "/usr/include/libio.h"
struct _IO_marker {
    struct _IO_marker *_next;
    struct _IO_FILE *_sbuf;



    int _pos;
};

#line 271 "/usr/include/libio.h"
struct _IO_FILE {
    int _flags;




    char *_IO_read_ptr;
    char *_IO_read_end;
    char *_IO_read_base;
    char *_IO_write_base;
    char *_IO_write_ptr;
    char *_IO_write_end;
    char *_IO_buf_base;
    char *_IO_buf_end;

    char *_IO_save_base;
    char *_IO_backup_base;
    char *_IO_save_end;

    struct _IO_marker *_markers;

    struct _IO_FILE *_chain;

    int _fileno;



    int _flags2;

    long int _old_offset;



    unsigned short int _cur_column;
    char _vtable_offset;
    char _shortbuf[1];



    void *_lock;

#line 319 "/usr/include/libio.h"
    long int _offset;

#line 328 "/usr/include/libio.h"
    void *__pad1;
    void *__pad2;
    void *__pad3;
    void *__pad4;
    unsigned long int __pad5;

    int _mode;

    char _unused2[20];
};

#line 99 "/usr/include/stdlib.h"
typedef struct {
    int quot;
    int rem; }
    div_t;




typedef struct {
    long int quot;
    long int rem; }
    ldiv_t;

#line 119 "/usr/include/stdlib.h"
typedef struct {
    long long int quot;
    long long int rem; }
    lldiv_t;

#line 349 "/usr/include/stdlib.h"
struct random_data {

    int *fptr;
    int *rptr;
    int *state;
    int rand_type;
    int rand_deg;
    int rand_sep;
    int *end_ptr;
};

#line 418 "/usr/include/stdlib.h"
struct drand48_data {

    unsigned short int __x[3];
    unsigned short int __old_x[3];
    unsigned short int __c;
    unsigned short int __init;
    unsigned long long int __a;
};

#line 68 "/usr/include/sys/select.h"
typedef struct {

#line 75 "/usr/include/sys/select.h"
    long int __fds_bits[16]; }


    fd_set;

#line 120 "/usr/include/time.h"
struct timespec {

    long int tv_sec;
    long int tv_nsec;
};

// type synonym definitions //////////////////////////////////////////

#line 50 "/opt/sce/inc/bits/pthreadtypes.h"
typedef unsigned long int pthread_t;

#line 65 "/opt/sce/inc/bits/pthreadtypes.h"
typedef struct __pthread_internal_list __pthread_list_t;

#line 151 "/opt/sce/inc/bits/pthreadtypes.h"
typedef unsigned int pthread_key_t;



typedef int pthread_once_t;

#line 212 "/opt/sce/inc/bits/pthreadtypes.h"
typedef volatile int pthread_spinlock_t;

#line 53 "/usr/include/_G_config.h"
typedef int _G_int16_t;
typedef int _G_int32_t;
typedef unsigned int _G_uint16_t;
typedef unsigned int _G_uint32_t;

#line 24 "/usr/include/bits/sigset.h"
typedef int __sig_atomic_t;

#line 31 "/usr/include/bits/types.h"
typedef unsigned char __u_char;
typedef unsigned short int __u_short;
typedef unsigned int __u_int;
typedef unsigned long int __u_long;


typedef char __int8_t;
typedef unsigned char __uint8_t;
typedef short int __int16_t;
typedef unsigned short int __uint16_t;
typedef int __int32_t;
typedef unsigned int __uint32_t;

typedef long int __int64_t;
typedef unsigned long int __uint64_t;

#line 53 "/usr/include/bits/types.h"
typedef long int __quad_t;
typedef unsigned long int __u_quad_t;

#line 134 "/usr/include/bits/types.h"
typedef unsigned long int __dev_t;
typedef unsigned int __uid_t;
typedef unsigned int __gid_t;
typedef unsigned long int __ino_t;
typedef unsigned long int __ino64_t;
typedef unsigned int __mode_t;
typedef unsigned long int __nlink_t;
typedef long int __off_t;
typedef long int __off64_t;
typedef int __pid_t;

typedef long int __clock_t;
typedef unsigned long int __rlim_t;
typedef unsigned long int __rlim64_t;
typedef unsigned int __id_t;
typedef long int __time_t;
typedef unsigned int __useconds_t;
typedef long int __suseconds_t;

typedef int __daddr_t;
typedef long int __swblk_t;
typedef int __key_t;


typedef int __clockid_t;


typedef void *__timer_t;


typedef long int __blksize_t;




typedef long int __blkcnt_t;
typedef long int __blkcnt64_t;


typedef unsigned long int __fsblkcnt_t;
typedef unsigned long int __fsblkcnt64_t;


typedef unsigned long int __fsfilcnt_t;
typedef unsigned long int __fsfilcnt64_t;

typedef long int __ssize_t;



typedef long int __loff_t;
typedef long int *__qaddr_t;
typedef char *__caddr_t;


typedef long int __intptr_t;


typedef unsigned int __socklen_t;

#line 180 "/usr/include/libio.h"
typedef void _IO_lock_t;

#line 341 "/usr/include/libio.h"
typedef struct _IO_FILE _IO_FILE;

#line 364 "/usr/include/libio.h"
typedef long int __io_read_fn(void *, char *, unsigned long int);

#line 372 "/usr/include/libio.h"
typedef long int __io_write_fn(void *, const char *, unsigned long int);

#line 381 "/usr/include/libio.h"
typedef int __io_seek_fn(void *, long int *, int);


typedef int __io_close_fn(void *);

#line 49 "/usr/include/stdio.h"
typedef struct _IO_FILE FILE;

#line 65 "/usr/include/stdio.h"
typedef struct _IO_FILE __FILE;

#line 742 "/usr/include/stdlib.h"
typedef int (*__compar_fn_t)(const void *, const void *);

#line 49 "/usr/include/sys/select.h"
typedef long int suseconds_t;

#line 55 "/usr/include/sys/select.h"
typedef long int __fd_mask;

#line 85 "/usr/include/sys/select.h"
typedef long int fd_mask;

#line 34 "/usr/include/sys/types.h"
typedef unsigned char u_char;
typedef unsigned short int u_short;
typedef unsigned int u_int;
typedef unsigned long int u_long;
typedef long int quad_t;
typedef unsigned long int u_quad_t;

#line 45 "/usr/include/sys/types.h"
typedef long int loff_t;



typedef unsigned long int ino_t;

#line 61 "/usr/include/sys/types.h"
typedef unsigned long int dev_t;




typedef unsigned int gid_t;




typedef unsigned int mode_t;




typedef unsigned long int nlink_t;




typedef unsigned int uid_t;

#line 87 "/usr/include/sys/types.h"
typedef long int off_t;

#line 99 "/usr/include/sys/types.h"
typedef int pid_t;

#line 105 "/usr/include/sys/types.h"
typedef unsigned int id_t;




typedef long int ssize_t;

#line 116 "/usr/include/sys/types.h"
typedef int daddr_t;
typedef char *caddr_t;

#line 123 "/usr/include/sys/types.h"
typedef int key_t;

#line 151 "/usr/include/sys/types.h"
typedef unsigned long int ulong;
typedef unsigned short int ushort;
typedef unsigned int uint;

#line 163 "/usr/include/sys/types.h"
typedef char int8_t;
typedef short int int16_t;
typedef int int32_t;

typedef long int int64_t;

#line 174 "/usr/include/sys/types.h"
typedef unsigned char u_int8_t;
typedef unsigned short int u_int16_t;
typedef unsigned int u_int32_t;

typedef unsigned long int u_int64_t;




typedef int register_t;

#line 236 "/usr/include/sys/types.h"
typedef long int blkcnt_t;



typedef unsigned long int fsblkcnt_t;



typedef unsigned long int fsfilcnt_t;

#line 76 "/usr/include/time.h"
typedef long int time_t;

#line 92 "/usr/include/time.h"
typedef int clockid_t;

#line 104 "/usr/include/time.h"
typedef void *timer_t;

#line 40 "/usr/lib/gcc/x86_64-redhat-linux/4.4.7/include/stdarg.h"
typedef void *__gnuc_va_list;

#line 211 "/usr/lib/gcc/x86_64-redhat-linux/4.4.7/include/stddef.h"
typedef unsigned long int size_t;

// class declarations ////////////////////////////////////////////////

#line 541 "ProdCons.h"
class IS;
class IR;
class C;
class Prod;
class Cons;
class Main;

// interface class definitions ///////////////////////////////////////

#line 14 "ProdCons.sc"
class IS
{
private:
public:

#line 557 "ProdCons.h"
    virtual ~IS(void){};

#line 16 "ProdCons.sc"
    virtual void Send(char) = 0;
private:
}; class IR
{
private:
public:

#line 568 "ProdCons.h"
    virtual ~IR(void){};

#line 20 "ProdCons.sc"
    virtual char Receive(void) = 0;
private:
};

// behavior and channel class definitions ////////////////////////////

#line 24 "ProdCons.sc"
class C : public _specc::channel, public IS, public IR
{
private:
public:

#line 584 "ProdCons.h"
    C();
    virtual ~C(void);
    char Receive(void);
    void Send(char);
private:

#line 28 "ProdCons.sc"
    _specc::event Ack;

#line 27 "ProdCons.sc"
    char Data;

#line 26 "ProdCons.sc"
    _specc::event Req;
};

#line 46 "ProdCons.sc"
class Prod : public _specc::behavior
{
private:

#line 46 "ProdCons.sc"
    IS (&Port);
public:

#line 610 "ProdCons.h"
    Prod(unsigned int _idcnt, IS (&Port));
    virtual ~Prod(void);
    void main(void);
private:

#line 51 "ProdCons.sc"
    char S[18];

#line 48 "ProdCons.sc"
    char X;
    int i;
};

#line 65 "ProdCons.sc"
class Cons : public _specc::behavior
{
private:

#line 65 "ProdCons.sc"
    IR (&Port);
public:

#line 633 "ProdCons.h"
    Cons(unsigned int _idcnt, IR (&Port));
    virtual ~Cons(void);
    void main(void);
private:

#line 67 "ProdCons.sc"
    char Y;
    int j;
};

#line 84 "ProdCons.sc"
class Main : public _specc::class_type
{
private:
public:

#line 650 "ProdCons.h"
    Main(unsigned int _idcnt);
    virtual ~Main(void);
    int main(void);
private:

#line 86 "ProdCons.sc"
    C Chan;

    Cons R;

#line 87 "ProdCons.sc"
    Prod S;
};

// variable and function declarations ////////////////////////////////

#line 33 "/usr/include/alloca.h"
extern "C" void *alloca(unsigned long int);

#line 27 "/usr/include/bits/sys_errlist.h"
extern int sys_nerr;
extern const char *const sys_errlist[];

#line 346 "/usr/include/libio.h"
extern struct _IO_FILE_plus _IO_2_1_stdin_;
extern struct _IO_FILE_plus _IO_2_1_stdout_;
extern struct _IO_FILE_plus _IO_2_1_stderr_;

#line 416 "/usr/include/libio.h"
extern "C" int __underflow(struct _IO_FILE *);
extern "C" int __uflow(struct _IO_FILE *);
extern "C" int __overflow(struct _IO_FILE *, int);

#line 460 "/usr/include/libio.h"
extern "C" int _IO_getc(struct _IO_FILE *);
extern "C" int _IO_putc(int, struct _IO_FILE *);
extern "C" int _IO_feof(struct _IO_FILE *);
extern "C" int _IO_ferror(struct _IO_FILE *);

extern "C" int _IO_peekc_locked(struct _IO_FILE *);

#line 471 "/usr/include/libio.h"
extern "C" void _IO_flockfile(struct _IO_FILE *);
extern "C" void _IO_funlockfile(struct _IO_FILE *);
extern "C" int _IO_ftrylockfile(struct _IO_FILE *);

#line 490 "/usr/include/libio.h"
extern "C" int _IO_vfscanf(struct _IO_FILE *, const char *, void *, int *);

extern "C" int _IO_vfprintf(struct _IO_FILE *, const char *, void *);

extern "C" long int _IO_padn(struct _IO_FILE *, int, long int);
extern "C" unsigned long int _IO_sgetn(struct _IO_FILE *, void *, unsigned long int);

extern "C" long int _IO_seekoff(struct _IO_FILE *, long int, int, int);
extern "C" long int _IO_seekpos(struct _IO_FILE *, long int, int);

extern "C" void _IO_free_backup_area(struct _IO_FILE *);

#line 165 "/usr/include/stdio.h"
extern struct _IO_FILE *stdin;
extern struct _IO_FILE *stdout;
extern struct _IO_FILE *stderr;

#line 177 "/usr/include/stdio.h"
extern "C" int remove(const char *);

extern "C" int rename(const char *, const char *);

#line 194 "/usr/include/stdio.h"
extern "C" struct _IO_FILE *tmpfile(void);

#line 208 "/usr/include/stdio.h"
extern "C" char *tmpnam(char *);

#line 214 "/usr/include/stdio.h"
extern "C" char *tmpnam_r(char *);

#line 226 "/usr/include/stdio.h"
extern "C" char *tempnam(const char *, const char *);

#line 236 "/usr/include/stdio.h"
extern "C" int fclose(struct _IO_FILE *);




extern "C" int fflush(struct _IO_FILE *);

#line 251 "/usr/include/stdio.h"
extern "C" int fflush_unlocked(struct _IO_FILE *);

#line 271 "/usr/include/stdio.h"
extern "C" struct _IO_FILE *fopen(const char *, const char *);

#line 277 "/usr/include/stdio.h"
extern "C" struct _IO_FILE *freopen(const char *, const char *, struct _IO_FILE *);

#line 305 "/usr/include/stdio.h"
extern "C" struct _IO_FILE *fdopen(int, const char *);

#line 331 "/usr/include/stdio.h"
extern "C" void setbuf(struct _IO_FILE *, char *);



extern "C" int setvbuf(struct _IO_FILE *, char *, int, unsigned long int);

#line 342 "/usr/include/stdio.h"
extern "C" void setbuffer(struct _IO_FILE *, char *, unsigned long int);



extern "C" void setlinebuf(struct _IO_FILE *);

#line 355 "/usr/include/stdio.h"
extern "C" int fprintf(struct _IO_FILE *, const char *, ...);

#line 361 "/usr/include/stdio.h"
extern "C" int printf(const char *, ...);

extern "C" int sprintf(char *, const char *, ...);

#line 370 "/usr/include/stdio.h"
extern "C" int vfprintf(struct _IO_FILE *, const char *, void *);

#line 376 "/usr/include/stdio.h"
extern "C" int vprintf(const char *, void *);

extern "C" int vsprintf(char *, const char *, void *);

#line 385 "/usr/include/stdio.h"
extern "C" int snprintf(char *, unsigned long int, const char *, ...);



extern "C" int vsnprintf(char *, unsigned long int, const char *, void *);

#line 429 "/usr/include/stdio.h"
extern "C" int fscanf(struct _IO_FILE *, const char *, ...);

#line 435 "/usr/include/stdio.h"
extern "C" int scanf(const char *, ...);

extern "C" int sscanf(const char *, const char *, ...);

#line 456 "/usr/include/stdio.h"
extern "C" int __isoc99_fscanf(struct _IO_FILE *, const char *, ...);

extern "C" int __isoc99_scanf(const char *, ...);
extern "C" int __isoc99_sscanf(const char *, const char *, ...);

#line 475 "/usr/include/stdio.h"
extern "C" int vfscanf(struct _IO_FILE *, const char *, void *);

#line 483 "/usr/include/stdio.h"
extern "C" int vscanf(const char *, void *);



extern "C" int vsscanf(const char *, const char *, void *);

#line 512 "/usr/include/stdio.h"
extern "C" int __isoc99_vfscanf(struct _IO_FILE *, const char *, void *);


extern "C" int __isoc99_vscanf(const char *, void *);

extern "C" int __isoc99_vsscanf(const char *, const char *, void *);

#line 535 "/usr/include/stdio.h"
extern "C" int fgetc(struct _IO_FILE *);
extern "C" int getc(struct _IO_FILE *);

#line 542 "/usr/include/stdio.h"
extern "C" int getchar(void);

#line 554 "/usr/include/stdio.h"
extern "C" int getc_unlocked(struct _IO_FILE *);
extern "C" int getchar_unlocked(void);

#line 565 "/usr/include/stdio.h"
extern "C" int fgetc_unlocked(struct _IO_FILE *);

#line 577 "/usr/include/stdio.h"
extern "C" int fputc(int, struct _IO_FILE *);
extern "C" int putc(int, struct _IO_FILE *);

#line 584 "/usr/include/stdio.h"
extern "C" int putchar(int);

#line 598 "/usr/include/stdio.h"
extern "C" int fputc_unlocked(int, struct _IO_FILE *);

#line 606 "/usr/include/stdio.h"
extern "C" int putc_unlocked(int, struct _IO_FILE *);
extern "C" int putchar_unlocked(int);

#line 614 "/usr/include/stdio.h"
extern "C" int getw(struct _IO_FILE *);


extern "C" int putw(int, struct _IO_FILE *);

#line 626 "/usr/include/stdio.h"
extern "C" char *fgets(char *, int, struct _IO_FILE *);

#line 634 "/usr/include/stdio.h"
extern "C" char *gets(char *);

#line 684 "/usr/include/stdio.h"
extern "C" int fputs(const char *, struct _IO_FILE *);

#line 690 "/usr/include/stdio.h"
extern "C" int puts(const char *);

#line 697 "/usr/include/stdio.h"
extern "C" int ungetc(int, struct _IO_FILE *);

#line 704 "/usr/include/stdio.h"
extern "C" unsigned long int fread(void *, unsigned long int, unsigned long int, struct _IO_FILE *);

#line 710 "/usr/include/stdio.h"
extern "C" unsigned long int fwrite(const void *, unsigned long int, unsigned long int, struct _IO_FILE *);

#line 732 "/usr/include/stdio.h"
extern "C" unsigned long int fread_unlocked(void *, unsigned long int, unsigned long int, struct _IO_FILE *);

extern "C" unsigned long int fwrite_unlocked(const void *, unsigned long int, unsigned long int, struct _IO_FILE *);

#line 744 "/usr/include/stdio.h"
extern "C" int fseek(struct _IO_FILE *, long int, int);




extern "C" long int ftell(struct _IO_FILE *);




extern "C" void rewind(struct _IO_FILE *);

#line 768 "/usr/include/stdio.h"
extern "C" int fseeko(struct _IO_FILE *, long int, int);




extern "C" long int ftello(struct _IO_FILE *);

#line 793 "/usr/include/stdio.h"
extern "C" int fgetpos(struct _IO_FILE *, _G_fpos_t *);




extern "C" int fsetpos(struct _IO_FILE *, const _G_fpos_t *);

#line 821 "/usr/include/stdio.h"
extern "C" void clearerr(struct _IO_FILE *);

extern "C" int feof(struct _IO_FILE *);

extern "C" int ferror(struct _IO_FILE *);




extern "C" void clearerr_unlocked(struct _IO_FILE *);
extern "C" int feof_unlocked(struct _IO_FILE *);
extern "C" int ferror_unlocked(struct _IO_FILE *);

#line 841 "/usr/include/stdio.h"
extern "C" void perror(const char *);

#line 853 "/usr/include/stdio.h"
extern "C" int fileno(struct _IO_FILE *);




extern "C" int fileno_unlocked(struct _IO_FILE *);

#line 868 "/usr/include/stdio.h"
extern "C" struct _IO_FILE *popen(const char *, const char *);

#line 874 "/usr/include/stdio.h"
extern "C" int pclose(struct _IO_FILE *);

#line 880 "/usr/include/stdio.h"
extern "C" char *ctermid(char *);

#line 908 "/usr/include/stdio.h"
extern "C" void flockfile(struct _IO_FILE *);



extern "C" int ftrylockfile(struct _IO_FILE *);


extern "C" void funlockfile(struct _IO_FILE *);

#line 140 "/usr/include/stdlib.h"
extern "C" unsigned long int __ctype_get_mb_cur_max(void);




extern "C" double atof(const char *);


extern "C" int atoi(const char *);


extern "C" long int atol(const char *);

#line 158 "/usr/include/stdlib.h"
extern "C" long long int atoll(const char *);

#line 165 "/usr/include/stdlib.h"
extern "C" double strtod(const char *, char **);

#line 173 "/usr/include/stdlib.h"
extern "C" float strtof(const char *, char **);


extern "C" long double strtold(const char *, char **);

#line 184 "/usr/include/stdlib.h"
extern "C" long int strtol(const char *, char **, int);



extern "C" unsigned long int strtoul(const char *, char **, int);

#line 210 "/usr/include/stdlib.h"
extern "C" long long int strtoll(const char *, char **, int);




extern "C" unsigned long long int strtoull(const char *, char **, int);

#line 311 "/usr/include/stdlib.h"
extern "C" char *l64a(long int);


extern "C" long int a64l(const char *);

#line 327 "/usr/include/stdlib.h"
extern "C" long int random(void);


extern "C" void srandom(unsigned int);

#line 336 "/usr/include/stdlib.h"
extern "C" char *initstate(unsigned int, char *, unsigned long int);




extern "C" char *setstate(char *);

#line 360 "/usr/include/stdlib.h"
extern "C" int random_r(struct random_data *, int *);


extern "C" int srandom_r(unsigned int, struct random_data *);


extern "C" int initstate_r(unsigned int, char *, unsigned long int, struct random_data *);




extern "C" int setstate_r(char *, struct random_data *);

#line 380 "/usr/include/stdlib.h"
extern "C" int rand(void);

extern "C" void srand(unsigned int);




extern "C" int rand_r(unsigned int *);

#line 395 "/usr/include/stdlib.h"
extern "C" double drand48(void);
extern "C" double erand48(unsigned short int [3]);


extern "C" long int lrand48(void);
extern "C" long int nrand48(unsigned short int [3]);



extern "C" long int mrand48(void);
extern "C" long int jrand48(unsigned short int [3]);



extern "C" void srand48(long int);
extern "C" unsigned short int *seed48(unsigned short int [3]);

extern "C" void lcong48(unsigned short int [7]);

#line 428 "/usr/include/stdlib.h"
extern "C" int drand48_r(struct drand48_data *, double *);

extern "C" int erand48_r(unsigned short int [3], struct drand48_data *, double *);




extern "C" int lrand48_r(struct drand48_data *, long int *);


extern "C" int nrand48_r(unsigned short int [3], struct drand48_data *, long int *);

#line 444 "/usr/include/stdlib.h"
extern "C" int mrand48_r(struct drand48_data *, long int *);


extern "C" int jrand48_r(unsigned short int [3], struct drand48_data *, long int *);

#line 453 "/usr/include/stdlib.h"
extern "C" int srand48_r(long int, struct drand48_data *);


extern "C" int seed48_r(unsigned short int [3], struct drand48_data *);


extern "C" int lcong48_r(unsigned short int [7], struct drand48_data *);

#line 471 "/usr/include/stdlib.h"
extern "C" void *malloc(unsigned long int);

extern "C" void *calloc(unsigned long int, unsigned long int);

#line 485 "/usr/include/stdlib.h"
extern "C" void *realloc(void *, unsigned long int);


extern "C" void free(void *);




extern "C" void cfree(void *);

#line 503 "/usr/include/stdlib.h"
extern "C" void *valloc(unsigned long int);




extern "C" int posix_memalign(void **, unsigned long int, unsigned long int);

#line 514 "/usr/include/stdlib.h"
extern "C" void abort(void);



extern "C" int atexit(void (*)(void));

#line 536 "/usr/include/stdlib.h"
extern "C" int on_exit(void (*)(int, void *), void *);

#line 544 "/usr/include/stdlib.h"
extern "C" void exit(int);

#line 560 "/usr/include/stdlib.h"
extern "C" void _Exit(int);

#line 567 "/usr/include/stdlib.h"
extern "C" char *getenv(const char *);




extern "C" char *__secure_getenv(const char *);

#line 579 "/usr/include/stdlib.h"
extern "C" int putenv(char *);

#line 585 "/usr/include/stdlib.h"
extern "C" int setenv(const char *, const char *, int);



extern "C" int unsetenv(const char *);

#line 596 "/usr/include/stdlib.h"
extern "C" int clearenv(void);

#line 606 "/usr/include/stdlib.h"
extern "C" char *mktemp(char *);

#line 620 "/usr/include/stdlib.h"
extern "C" int mkstemp(char *);

#line 642 "/usr/include/stdlib.h"
extern "C" int mkstemps(char *, int);

#line 663 "/usr/include/stdlib.h"
extern "C" char *mkdtemp(char *);

#line 717 "/usr/include/stdlib.h"
extern "C" int system(const char *);

#line 734 "/usr/include/stdlib.h"
extern "C" char *realpath(const char *, char *);

#line 755 "/usr/include/stdlib.h"
extern "C" void *bsearch(const void *, const void *, unsigned long int, unsigned long int, int (*)(const void *, const void *));

#line 761 "/usr/include/stdlib.h"
extern "C" void qsort(void *, unsigned long int, unsigned long int, int (*)(const void *, const void *));

#line 771 "/usr/include/stdlib.h"
extern "C" int abs(int);
extern "C" long int labs(long int);



extern "C" long long int llabs(long long int);

#line 785 "/usr/include/stdlib.h"
extern "C" div_t div(int, int);

extern "C" ldiv_t ldiv(long int, long int);

#line 793 "/usr/include/stdlib.h"
extern "C" lldiv_t lldiv(long long int, long long int);

#line 808 "/usr/include/stdlib.h"
extern "C" char *ecvt(double, int, int *, int *);

#line 814 "/usr/include/stdlib.h"
extern "C" char *fcvt(double, int, int *, int *);

#line 820 "/usr/include/stdlib.h"
extern "C" char *gcvt(double, int, char *);

#line 826 "/usr/include/stdlib.h"
extern "C" char *qecvt(long double, int, int *, int *);


extern "C" char *qfcvt(long double, int, int *, int *);


extern "C" char *qgcvt(long double, int, char *);

#line 838 "/usr/include/stdlib.h"
extern "C" int ecvt_r(double, int, int *, int *, char *, unsigned long int);


extern "C" int fcvt_r(double, int, int *, int *, char *, unsigned long int);



extern "C" int qecvt_r(long double, int, int *, int *, char *, unsigned long int);



extern "C" int qfcvt_r(long double, int, int *, int *, char *, unsigned long int);

#line 860 "/usr/include/stdlib.h"
extern "C" int mblen(const char *, unsigned long int);


extern "C" int mbtowc(int *, const char *, unsigned long int);



extern "C" int wctomb(char *, int);



extern "C" unsigned long int mbstowcs(int *, const char *, unsigned long int);


extern "C" unsigned long int wcstombs(char *, const int *, unsigned long int);

#line 885 "/usr/include/stdlib.h"
extern "C" int rpmatch(const char *);

#line 948 "/usr/include/stdlib.h"
extern "C" int getloadavg(double [], int);

#line 109 "/usr/include/sys/select.h"
extern "C" int select(int, fd_set *, fd_set *, fd_set *, struct timeval *);

#line 121 "/usr/include/sys/select.h"
extern "C" int pselect(int, fd_set *, fd_set *, fd_set *, const struct timespec *, const __sigset_t *);

#line 1249 "ProdCons.h"
void _scc_bit4_err_handle(const _bit4&);

//////////////////////////////////////////////////////////////////////
// End of file ProdCons.h
//////////////////////////////////////////////////////////////////////
