//////////////////////////////////////////////////////////////////////
// C++ source file generated by SpecC V2.2.1
// Design: HelloWorld
// File:   HelloWorld.cc
// Time:   Wed Apr 12 13:57:20 2017
//////////////////////////////////////////////////////////////////////

// Note: User-defined include files are inlined in this file.

// Note: System-defined include files are inlined in this file.

#include "HelloWorld.h"


unsigned int _IDcnt = 0;
// behavior class definitions ////////////////////////////////////////

Main::Main(unsigned int _idcnt)
    : _specc::class_type(_idcnt)
{   
}

Main::~Main(void)
{   
}

#line 15 "HelloWorld.sc"
int Main::main(void)
{   
    printf("Hello World!\n");
    return (0);
}

#line 35 "HelloWorld.cc"
Main _scc_main(_IDcnt);

int main(void)
{   
    int _scc_main_return;
    
    _specc::start();
    _scc_main_return = _scc_main.main();
    _specc::end();
    return(_scc_main_return);
}

void _scc_bit4_err_handle(
    const _bit4& bit4vec)
{   
    char temp_bits[1024], *p;
    p=bit2str(2,&temp_bits[1023], bit4vec);
    _specc::abort(
	"ERROR:\t Casting a bit4 vector failed \n"
	"Bit4 vector contains X/Z values %s\n"
	"Simulation aborted.\n", p);
	
}

//////////////////////////////////////////////////////////////////////
// End of file HelloWorld.cc
//////////////////////////////////////////////////////////////////////
