//////////////////////////////////////////////////////////////////////
// C++ header file generated by SpecC V2.2.1
// Design: HelloWorld
// File:   HelloWorld.h
// Time:   Wed Apr 12 13:57:20 2017
//////////////////////////////////////////////////////////////////////

// Note: User-defined include files are inlined in this file.

// Note: System-defined include files are inlined in this file.

#include <specc.h>

// named user-defined type declarations //////////////////////////////

#line 170 "/usr/include/libio.h"
struct _IO_jump_t;

#line 20 "HelloWorld.h"
struct _IO_marker;
struct _IO_FILE;

#line 344 "/usr/include/libio.h"
struct _IO_FILE_plus;

// named enumerator type definitions /////////////////////////////////

#line 206 "/usr/include/libio.h"
enum __codecvt_result {

    __codecvt_ok=0,
    __codecvt_partial=1,
    __codecvt_error=2,
    __codecvt_noconv=3
};

// struct/union type definitions /////////////////////////////////////

#line 84 "/usr/include/wchar.h"
typedef struct {
    int __count;

#line 94 "/usr/include/wchar.h"
    union { unsigned int __wch; char __wchb[4]; } __value; }
    __mbstate_t;

#line 23 "/usr/include/_G_config.h"
typedef struct {
    long int __pos;
    __mbstate_t __state; }
    _G_fpos_t;

typedef struct {
    long int __pos;
    __mbstate_t __state; }
    _G_fpos64_t;

#line 144 "/usr/include/bits/types.h"
typedef struct { int __val[2]; } __fsid_t;

#line 186 "/usr/include/libio.h"
struct _IO_marker {
    struct _IO_marker *_next;
    struct _IO_FILE *_sbuf;



    int _pos;
};

#line 271 "/usr/include/libio.h"
struct _IO_FILE {
    int _flags;




    char *_IO_read_ptr;
    char *_IO_read_end;
    char *_IO_read_base;
    char *_IO_write_base;
    char *_IO_write_ptr;
    char *_IO_write_end;
    char *_IO_buf_base;
    char *_IO_buf_end;

    char *_IO_save_base;
    char *_IO_backup_base;
    char *_IO_save_end;

    struct _IO_marker *_markers;

    struct _IO_FILE *_chain;

    int _fileno;



    int _flags2;

    long int _old_offset;



    unsigned short int _cur_column;
    char _vtable_offset;
    char _shortbuf[1];



    void *_lock;

#line 319 "/usr/include/libio.h"
    long int _offset;

#line 328 "/usr/include/libio.h"
    void *__pad1;
    void *__pad2;
    void *__pad3;
    void *__pad4;
    unsigned long int __pad5;

    int _mode;

    char _unused2[20];
};

// type synonym definitions //////////////////////////////////////////

#line 53 "/usr/include/_G_config.h"
typedef int _G_int16_t;
typedef int _G_int32_t;
typedef unsigned int _G_uint16_t;
typedef unsigned int _G_uint32_t;

#line 31 "/usr/include/bits/types.h"
typedef unsigned char __u_char;
typedef unsigned short int __u_short;
typedef unsigned int __u_int;
typedef unsigned long int __u_long;


typedef char __int8_t;
typedef unsigned char __uint8_t;
typedef short int __int16_t;
typedef unsigned short int __uint16_t;
typedef int __int32_t;
typedef unsigned int __uint32_t;

typedef long int __int64_t;
typedef unsigned long int __uint64_t;

#line 53 "/usr/include/bits/types.h"
typedef long int __quad_t;
typedef unsigned long int __u_quad_t;

#line 134 "/usr/include/bits/types.h"
typedef unsigned long int __dev_t;
typedef unsigned int __uid_t;
typedef unsigned int __gid_t;
typedef unsigned long int __ino_t;
typedef unsigned long int __ino64_t;
typedef unsigned int __mode_t;
typedef unsigned long int __nlink_t;
typedef long int __off_t;
typedef long int __off64_t;
typedef int __pid_t;

typedef long int __clock_t;
typedef unsigned long int __rlim_t;
typedef unsigned long int __rlim64_t;
typedef unsigned int __id_t;
typedef long int __time_t;
typedef unsigned int __useconds_t;
typedef long int __suseconds_t;

typedef int __daddr_t;
typedef long int __swblk_t;
typedef int __key_t;


typedef int __clockid_t;


typedef void *__timer_t;


typedef long int __blksize_t;




typedef long int __blkcnt_t;
typedef long int __blkcnt64_t;


typedef unsigned long int __fsblkcnt_t;
typedef unsigned long int __fsblkcnt64_t;


typedef unsigned long int __fsfilcnt_t;
typedef unsigned long int __fsfilcnt64_t;

typedef long int __ssize_t;



typedef long int __loff_t;
typedef long int *__qaddr_t;
typedef char *__caddr_t;


typedef long int __intptr_t;


typedef unsigned int __socklen_t;

#line 180 "/usr/include/libio.h"
typedef void _IO_lock_t;

#line 341 "/usr/include/libio.h"
typedef struct _IO_FILE _IO_FILE;

#line 364 "/usr/include/libio.h"
typedef long int __io_read_fn(void *, char *, unsigned long int);

#line 372 "/usr/include/libio.h"
typedef long int __io_write_fn(void *, const char *, unsigned long int);

#line 381 "/usr/include/libio.h"
typedef int __io_seek_fn(void *, long int *, int);


typedef int __io_close_fn(void *);

#line 49 "/usr/include/stdio.h"
typedef struct _IO_FILE FILE;

#line 65 "/usr/include/stdio.h"
typedef struct _IO_FILE __FILE;

#line 40 "/usr/lib/gcc/x86_64-redhat-linux/4.4.7/include/stdarg.h"
typedef void *__gnuc_va_list;

#line 211 "/usr/lib/gcc/x86_64-redhat-linux/4.4.7/include/stddef.h"
typedef unsigned long int size_t;

// class declarations ////////////////////////////////////////////////

#line 251 "HelloWorld.h"
class Main;

// behavior and channel class definitions ////////////////////////////

#line 13 "HelloWorld.sc"
class Main : public _specc::class_type
{
private:
public:

#line 262 "HelloWorld.h"
    Main(unsigned int _idcnt);
    virtual ~Main(void);
    int main(void);
private:
};

// variable and function declarations ////////////////////////////////

#line 27 "/usr/include/bits/sys_errlist.h"
extern int sys_nerr;
extern const char *const sys_errlist[];

#line 346 "/usr/include/libio.h"
extern struct _IO_FILE_plus _IO_2_1_stdin_;
extern struct _IO_FILE_plus _IO_2_1_stdout_;
extern struct _IO_FILE_plus _IO_2_1_stderr_;

#line 416 "/usr/include/libio.h"
extern "C" int __underflow(struct _IO_FILE *);
extern "C" int __uflow(struct _IO_FILE *);
extern "C" int __overflow(struct _IO_FILE *, int);

#line 460 "/usr/include/libio.h"
extern "C" int _IO_getc(struct _IO_FILE *);
extern "C" int _IO_putc(int, struct _IO_FILE *);
extern "C" int _IO_feof(struct _IO_FILE *);
extern "C" int _IO_ferror(struct _IO_FILE *);

extern "C" int _IO_peekc_locked(struct _IO_FILE *);

#line 471 "/usr/include/libio.h"
extern "C" void _IO_flockfile(struct _IO_FILE *);
extern "C" void _IO_funlockfile(struct _IO_FILE *);
extern "C" int _IO_ftrylockfile(struct _IO_FILE *);

#line 490 "/usr/include/libio.h"
extern "C" int _IO_vfscanf(struct _IO_FILE *, const char *, void *, int *);

extern "C" int _IO_vfprintf(struct _IO_FILE *, const char *, void *);

extern "C" long int _IO_padn(struct _IO_FILE *, int, long int);
extern "C" unsigned long int _IO_sgetn(struct _IO_FILE *, void *, unsigned long int);

extern "C" long int _IO_seekoff(struct _IO_FILE *, long int, int, int);
extern "C" long int _IO_seekpos(struct _IO_FILE *, long int, int);

extern "C" void _IO_free_backup_area(struct _IO_FILE *);

#line 165 "/usr/include/stdio.h"
extern struct _IO_FILE *stdin;
extern struct _IO_FILE *stdout;
extern struct _IO_FILE *stderr;

#line 177 "/usr/include/stdio.h"
extern "C" int remove(const char *);

extern "C" int rename(const char *, const char *);

#line 194 "/usr/include/stdio.h"
extern "C" struct _IO_FILE *tmpfile(void);

#line 208 "/usr/include/stdio.h"
extern "C" char *tmpnam(char *);

#line 214 "/usr/include/stdio.h"
extern "C" char *tmpnam_r(char *);

#line 226 "/usr/include/stdio.h"
extern "C" char *tempnam(const char *, const char *);

#line 236 "/usr/include/stdio.h"
extern "C" int fclose(struct _IO_FILE *);




extern "C" int fflush(struct _IO_FILE *);

#line 251 "/usr/include/stdio.h"
extern "C" int fflush_unlocked(struct _IO_FILE *);

#line 271 "/usr/include/stdio.h"
extern "C" struct _IO_FILE *fopen(const char *, const char *);

#line 277 "/usr/include/stdio.h"
extern "C" struct _IO_FILE *freopen(const char *, const char *, struct _IO_FILE *);

#line 305 "/usr/include/stdio.h"
extern "C" struct _IO_FILE *fdopen(int, const char *);

#line 331 "/usr/include/stdio.h"
extern "C" void setbuf(struct _IO_FILE *, char *);



extern "C" int setvbuf(struct _IO_FILE *, char *, int, unsigned long int);

#line 342 "/usr/include/stdio.h"
extern "C" void setbuffer(struct _IO_FILE *, char *, unsigned long int);



extern "C" void setlinebuf(struct _IO_FILE *);

#line 355 "/usr/include/stdio.h"
extern "C" int fprintf(struct _IO_FILE *, const char *, ...);

#line 361 "/usr/include/stdio.h"
extern "C" int printf(const char *, ...);

extern "C" int sprintf(char *, const char *, ...);

#line 370 "/usr/include/stdio.h"
extern "C" int vfprintf(struct _IO_FILE *, const char *, void *);

#line 376 "/usr/include/stdio.h"
extern "C" int vprintf(const char *, void *);

extern "C" int vsprintf(char *, const char *, void *);

#line 385 "/usr/include/stdio.h"
extern "C" int snprintf(char *, unsigned long int, const char *, ...);



extern "C" int vsnprintf(char *, unsigned long int, const char *, void *);

#line 429 "/usr/include/stdio.h"
extern "C" int fscanf(struct _IO_FILE *, const char *, ...);

#line 435 "/usr/include/stdio.h"
extern "C" int scanf(const char *, ...);

extern "C" int sscanf(const char *, const char *, ...);

#line 456 "/usr/include/stdio.h"
extern "C" int __isoc99_fscanf(struct _IO_FILE *, const char *, ...);

extern "C" int __isoc99_scanf(const char *, ...);
extern "C" int __isoc99_sscanf(const char *, const char *, ...);

#line 475 "/usr/include/stdio.h"
extern "C" int vfscanf(struct _IO_FILE *, const char *, void *);

#line 483 "/usr/include/stdio.h"
extern "C" int vscanf(const char *, void *);



extern "C" int vsscanf(const char *, const char *, void *);

#line 512 "/usr/include/stdio.h"
extern "C" int __isoc99_vfscanf(struct _IO_FILE *, const char *, void *);


extern "C" int __isoc99_vscanf(const char *, void *);

extern "C" int __isoc99_vsscanf(const char *, const char *, void *);

#line 535 "/usr/include/stdio.h"
extern "C" int fgetc(struct _IO_FILE *);
extern "C" int getc(struct _IO_FILE *);

#line 542 "/usr/include/stdio.h"
extern "C" int getchar(void);

#line 554 "/usr/include/stdio.h"
extern "C" int getc_unlocked(struct _IO_FILE *);
extern "C" int getchar_unlocked(void);

#line 565 "/usr/include/stdio.h"
extern "C" int fgetc_unlocked(struct _IO_FILE *);

#line 577 "/usr/include/stdio.h"
extern "C" int fputc(int, struct _IO_FILE *);
extern "C" int putc(int, struct _IO_FILE *);

#line 584 "/usr/include/stdio.h"
extern "C" int putchar(int);

#line 598 "/usr/include/stdio.h"
extern "C" int fputc_unlocked(int, struct _IO_FILE *);

#line 606 "/usr/include/stdio.h"
extern "C" int putc_unlocked(int, struct _IO_FILE *);
extern "C" int putchar_unlocked(int);

#line 614 "/usr/include/stdio.h"
extern "C" int getw(struct _IO_FILE *);


extern "C" int putw(int, struct _IO_FILE *);

#line 626 "/usr/include/stdio.h"
extern "C" char *fgets(char *, int, struct _IO_FILE *);

#line 634 "/usr/include/stdio.h"
extern "C" char *gets(char *);

#line 684 "/usr/include/stdio.h"
extern "C" int fputs(const char *, struct _IO_FILE *);

#line 690 "/usr/include/stdio.h"
extern "C" int puts(const char *);

#line 697 "/usr/include/stdio.h"
extern "C" int ungetc(int, struct _IO_FILE *);

#line 704 "/usr/include/stdio.h"
extern "C" unsigned long int fread(void *, unsigned long int, unsigned long int, struct _IO_FILE *);

#line 710 "/usr/include/stdio.h"
extern "C" unsigned long int fwrite(const void *, unsigned long int, unsigned long int, struct _IO_FILE *);

#line 732 "/usr/include/stdio.h"
extern "C" unsigned long int fread_unlocked(void *, unsigned long int, unsigned long int, struct _IO_FILE *);

extern "C" unsigned long int fwrite_unlocked(const void *, unsigned long int, unsigned long int, struct _IO_FILE *);

#line 744 "/usr/include/stdio.h"
extern "C" int fseek(struct _IO_FILE *, long int, int);




extern "C" long int ftell(struct _IO_FILE *);




extern "C" void rewind(struct _IO_FILE *);

#line 768 "/usr/include/stdio.h"
extern "C" int fseeko(struct _IO_FILE *, long int, int);




extern "C" long int ftello(struct _IO_FILE *);

#line 793 "/usr/include/stdio.h"
extern "C" int fgetpos(struct _IO_FILE *, _G_fpos_t *);




extern "C" int fsetpos(struct _IO_FILE *, const _G_fpos_t *);

#line 821 "/usr/include/stdio.h"
extern "C" void clearerr(struct _IO_FILE *);

extern "C" int feof(struct _IO_FILE *);

extern "C" int ferror(struct _IO_FILE *);




extern "C" void clearerr_unlocked(struct _IO_FILE *);
extern "C" int feof_unlocked(struct _IO_FILE *);
extern "C" int ferror_unlocked(struct _IO_FILE *);

#line 841 "/usr/include/stdio.h"
extern "C" void perror(const char *);

#line 853 "/usr/include/stdio.h"
extern "C" int fileno(struct _IO_FILE *);




extern "C" int fileno_unlocked(struct _IO_FILE *);

#line 868 "/usr/include/stdio.h"
extern "C" struct _IO_FILE *popen(const char *, const char *);

#line 874 "/usr/include/stdio.h"
extern "C" int pclose(struct _IO_FILE *);

#line 880 "/usr/include/stdio.h"
extern "C" char *ctermid(char *);

#line 908 "/usr/include/stdio.h"
extern "C" void flockfile(struct _IO_FILE *);



extern "C" int ftrylockfile(struct _IO_FILE *);


extern "C" void funlockfile(struct _IO_FILE *);

#line 555 "HelloWorld.h"
void _scc_bit4_err_handle(const _bit4&);

//////////////////////////////////////////////////////////////////////
// End of file HelloWorld.h
//////////////////////////////////////////////////////////////////////
