//////////////////////////////////////////////////////////////////////
// C++ header file generated by SpecC V2.2.1
// Design: cannyx
// File:   cannyx.h
// Time:   Wed May 31 00:00:00 2017
//////////////////////////////////////////////////////////////////////

// Note: User-defined include files are inlined in this file.

// Note: System-defined include files are inlined in this file.

#include <specc.h>

// named user-defined type declarations //////////////////////////////

struct __pthread_internal_list;
struct timeval;

#line 170 "/usr/include/libio.h"
struct _IO_jump_t;

#line 23 "cannyx.h"
struct _IO_marker;
struct _IO_FILE;

#line 344 "/usr/include/libio.h"
struct _IO_FILE_plus;

#line 30 "cannyx.h"
struct exception;
struct random_data;
struct drand48_data;
struct timespec;

// named enumerator type definitions /////////////////////////////////

#line 206 "/usr/include/libio.h"
enum __codecvt_result {

    __codecvt_ok=0,
    __codecvt_partial=1,
    __codecvt_error=2,
    __codecvt_noconv=3
};

// unnamed enumerator type definitions ///////////////////////////////

#line 199 "/usr/include/math.h"
enum {
    FP_NAN=0,

    FP_INFINITE=1,

    FP_ZERO=2,

    FP_SUBNORMAL=3,

    FP_NORMAL=4
};

#line 292 "/usr/include/math.h"
typedef enum {
    _IEEE_=-1,
    _SVID_=0,
    _XOPEN_=1,
    _POSIX_=2,
    _ISOC_=3 }
    _LIB_VERSION_TYPE;

// struct/union type definitions /////////////////////////////////////

#line 43 "/opt/sce/inc/bits/huge_val.h"
typedef union { unsigned char __c[8]; double __d; } __huge_val_t;

#line 41 "/opt/sce/inc/bits/huge_valf.h"
typedef union { unsigned char __c[4]; float __f; } __huge_valf_t;

#line 54 "/opt/sce/inc/bits/pthreadtypes.h"
typedef union {
    char __size[56];
    long int __align; }
    pthread_attr_t;



struct __pthread_internal_list {

    struct __pthread_internal_list *__prev;
    struct __pthread_internal_list *__next;
};

#line 77 "/opt/sce/inc/bits/pthreadtypes.h"
typedef union {

#line 101 "/opt/sce/inc/bits/pthreadtypes.h"
    struct __pthread_mutex_s { int __lock; unsigned int __count; int __owner; unsigned int __nusers; int __kind; int __spins; struct __pthread_internal_list __list; } __data;
    char __size[40];
    long int __align; }
    pthread_mutex_t;


typedef union {
    char __size[4];
    int __align; }
    pthread_mutexattr_t;

#line 116 "/opt/sce/inc/bits/pthreadtypes.h"
typedef union {

#line 133 "/opt/sce/inc/bits/pthreadtypes.h"
    struct { int __lock; unsigned int __futex; int __total_seq1; int __total_seq2; int __wakeup_seq1; int __wakeup_seq2; int __woken_seq1; int __woken_seq2; void *__mutex; unsigned int __nwaiters; unsigned int __broadcast_seq; } __data;
    char __size[48];




    void *__align1;
    long int __align2; }
    pthread_cond_t;


typedef union {
    char __size[4];
    int __align; }
    pthread_condattr_t;

#line 162 "/opt/sce/inc/bits/pthreadtypes.h"
typedef union {

#line 179 "/opt/sce/inc/bits/pthreadtypes.h"
    struct { int __lock; unsigned int __nr_readers; unsigned int __readers_wakeup; unsigned int __writer_wakeup; unsigned int __nr_readers_queued; unsigned int __nr_writers_queued; int __writer; int __shared; unsigned long int __pad1; unsigned long int __pad2; unsigned int __flags; } __data;

#line 198 "/opt/sce/inc/bits/pthreadtypes.h"
    char __size[56];
    long int __align; }
    pthread_rwlock_t;


typedef union {
    char __size[8];
    long int __align; }
    pthread_rwlockattr_t;

#line 218 "/opt/sce/inc/bits/pthreadtypes.h"
typedef union {
    char __size[32];
    long int __align; }
    pthread_barrier_t;


typedef union {
    char __size[4];
    int __align; }
    pthread_barrierattr_t;

#line 84 "/usr/include/wchar.h"
typedef struct {
    int __count;

#line 94 "/usr/include/wchar.h"
    union { unsigned int __wch; char __wchb[4]; } __value; }
    __mbstate_t;

#line 23 "/usr/include/_G_config.h"
typedef struct {
    long int __pos;
    __mbstate_t __state; }
    _G_fpos_t;

typedef struct {
    long int __pos;
    __mbstate_t __state; }
    _G_fpos64_t;

#line 30 "/usr/include/bits/sigset.h"
typedef struct {
    unsigned long int __val[16]; }
    __sigset_t;

#line 75 "/usr/include/bits/time.h"
struct timeval {

    long int tv_sec;
    long int tv_usec;
};

#line 144 "/usr/include/bits/types.h"
typedef struct { int __val[2]; } __fsid_t;

#line 186 "/usr/include/libio.h"
struct _IO_marker {
    struct _IO_marker *_next;
    struct _IO_FILE *_sbuf;



    int _pos;
};

#line 271 "/usr/include/libio.h"
struct _IO_FILE {
    int _flags;




    char *_IO_read_ptr;
    char *_IO_read_end;
    char *_IO_read_base;
    char *_IO_write_base;
    char *_IO_write_ptr;
    char *_IO_write_end;
    char *_IO_buf_base;
    char *_IO_buf_end;

    char *_IO_save_base;
    char *_IO_backup_base;
    char *_IO_save_end;

    struct _IO_marker *_markers;

    struct _IO_FILE *_chain;

    int _fileno;



    int _flags2;

    long int _old_offset;



    unsigned short int _cur_column;
    char _vtable_offset;
    char _shortbuf[1];



    void *_lock;

#line 319 "/usr/include/libio.h"
    long int _offset;

#line 328 "/usr/include/libio.h"
    void *__pad1;
    void *__pad2;
    void *__pad3;
    void *__pad4;
    unsigned long int __pad5;

    int _mode;

    char _unused2[20];
};

#line 316 "/usr/include/math.h"
struct exception {


    int type;
    char *name;
    double arg1;
    double arg2;
    double retval;
};

#line 99 "/usr/include/stdlib.h"
typedef struct {
    int quot;
    int rem; }
    div_t;




typedef struct {
    long int quot;
    long int rem; }
    ldiv_t;

#line 119 "/usr/include/stdlib.h"
typedef struct {
    long long int quot;
    long long int rem; }
    lldiv_t;

#line 349 "/usr/include/stdlib.h"
struct random_data {

    int *fptr;
    int *rptr;
    int *state;
    int rand_type;
    int rand_deg;
    int rand_sep;
    int *end_ptr;
};

#line 418 "/usr/include/stdlib.h"
struct drand48_data {

    unsigned short int __x[3];
    unsigned short int __old_x[3];
    unsigned short int __c;
    unsigned short int __init;
    unsigned long long int __a;
};

#line 68 "/usr/include/sys/select.h"
typedef struct {

#line 75 "/usr/include/sys/select.h"
    long int __fds_bits[16]; }


    fd_set;

#line 120 "/usr/include/time.h"
struct timespec {

    long int tv_sec;
    long int tv_nsec;
};

// type synonym definitions //////////////////////////////////////////

#line 50 "/opt/sce/inc/bits/pthreadtypes.h"
typedef unsigned long int pthread_t;

#line 65 "/opt/sce/inc/bits/pthreadtypes.h"
typedef struct __pthread_internal_list __pthread_list_t;

#line 151 "/opt/sce/inc/bits/pthreadtypes.h"
typedef unsigned int pthread_key_t;



typedef int pthread_once_t;

#line 212 "/opt/sce/inc/bits/pthreadtypes.h"
typedef volatile int pthread_spinlock_t;

#line 57 "/opt/sce/inc/sim/time.sh"
typedef unsigned long long int sim_time;

typedef unsigned long long int sim_delta;

typedef char sim_time_string[21];

#line 53 "/usr/include/_G_config.h"
typedef int _G_int16_t;
typedef int _G_int32_t;
typedef unsigned int _G_uint16_t;
typedef unsigned int _G_uint32_t;

#line 31 "/usr/include/bits/mathdef.h"
typedef float float_t;
typedef double double_t;

#line 24 "/usr/include/bits/sigset.h"
typedef int __sig_atomic_t;

#line 31 "/usr/include/bits/types.h"
typedef unsigned char __u_char;
typedef unsigned short int __u_short;
typedef unsigned int __u_int;
typedef unsigned long int __u_long;


typedef char __int8_t;
typedef unsigned char __uint8_t;
typedef short int __int16_t;
typedef unsigned short int __uint16_t;
typedef int __int32_t;
typedef unsigned int __uint32_t;

typedef long int __int64_t;
typedef unsigned long int __uint64_t;

#line 53 "/usr/include/bits/types.h"
typedef long int __quad_t;
typedef unsigned long int __u_quad_t;

#line 134 "/usr/include/bits/types.h"
typedef unsigned long int __dev_t;
typedef unsigned int __uid_t;
typedef unsigned int __gid_t;
typedef unsigned long int __ino_t;
typedef unsigned long int __ino64_t;
typedef unsigned int __mode_t;
typedef unsigned long int __nlink_t;
typedef long int __off_t;
typedef long int __off64_t;
typedef int __pid_t;

typedef long int __clock_t;
typedef unsigned long int __rlim_t;
typedef unsigned long int __rlim64_t;
typedef unsigned int __id_t;
typedef long int __time_t;
typedef unsigned int __useconds_t;
typedef long int __suseconds_t;

typedef int __daddr_t;
typedef long int __swblk_t;
typedef int __key_t;


typedef int __clockid_t;


typedef void *__timer_t;


typedef long int __blksize_t;




typedef long int __blkcnt_t;
typedef long int __blkcnt64_t;


typedef unsigned long int __fsblkcnt_t;
typedef unsigned long int __fsblkcnt64_t;


typedef unsigned long int __fsfilcnt_t;
typedef unsigned long int __fsfilcnt64_t;

typedef long int __ssize_t;



typedef long int __loff_t;
typedef long int *__qaddr_t;
typedef char *__caddr_t;


typedef long int __intptr_t;


typedef unsigned int __socklen_t;

#line 180 "/usr/include/libio.h"
typedef void _IO_lock_t;

#line 341 "/usr/include/libio.h"
typedef struct _IO_FILE _IO_FILE;

#line 364 "/usr/include/libio.h"
typedef long int __io_read_fn(void *, char *, unsigned long int);

#line 372 "/usr/include/libio.h"
typedef long int __io_write_fn(void *, const char *, unsigned long int);

#line 381 "/usr/include/libio.h"
typedef int __io_seek_fn(void *, long int *, int);


typedef int __io_close_fn(void *);

#line 49 "/usr/include/stdio.h"
typedef struct _IO_FILE FILE;

#line 65 "/usr/include/stdio.h"
typedef struct _IO_FILE __FILE;

#line 742 "/usr/include/stdlib.h"
typedef int (*__compar_fn_t)(const void *, const void *);

#line 49 "/usr/include/sys/select.h"
typedef long int suseconds_t;

#line 55 "/usr/include/sys/select.h"
typedef long int __fd_mask;

#line 85 "/usr/include/sys/select.h"
typedef long int fd_mask;

#line 34 "/usr/include/sys/types.h"
typedef unsigned char u_char;
typedef unsigned short int u_short;
typedef unsigned int u_int;
typedef unsigned long int u_long;
typedef long int quad_t;
typedef unsigned long int u_quad_t;

#line 45 "/usr/include/sys/types.h"
typedef long int loff_t;



typedef unsigned long int ino_t;

#line 61 "/usr/include/sys/types.h"
typedef unsigned long int dev_t;




typedef unsigned int gid_t;




typedef unsigned int mode_t;




typedef unsigned long int nlink_t;




typedef unsigned int uid_t;

#line 87 "/usr/include/sys/types.h"
typedef long int off_t;

#line 99 "/usr/include/sys/types.h"
typedef int pid_t;

#line 105 "/usr/include/sys/types.h"
typedef unsigned int id_t;




typedef long int ssize_t;

#line 116 "/usr/include/sys/types.h"
typedef int daddr_t;
typedef char *caddr_t;

#line 123 "/usr/include/sys/types.h"
typedef int key_t;

#line 151 "/usr/include/sys/types.h"
typedef unsigned long int ulong;
typedef unsigned short int ushort;
typedef unsigned int uint;

#line 163 "/usr/include/sys/types.h"
typedef char int8_t;
typedef short int int16_t;
typedef int int32_t;

typedef long int int64_t;

#line 174 "/usr/include/sys/types.h"
typedef unsigned char u_int8_t;
typedef unsigned short int u_int16_t;
typedef unsigned int u_int32_t;

typedef unsigned long int u_int64_t;




typedef int register_t;

#line 236 "/usr/include/sys/types.h"
typedef long int blkcnt_t;



typedef unsigned long int fsblkcnt_t;



typedef unsigned long int fsfilcnt_t;

#line 76 "/usr/include/time.h"
typedef long int time_t;

#line 92 "/usr/include/time.h"
typedef int clockid_t;

#line 104 "/usr/include/time.h"
typedef void *timer_t;

#line 40 "/usr/lib/gcc/x86_64-redhat-linux/4.4.7/include/stdarg.h"
typedef void *__gnuc_va_list;

#line 149 "/usr/lib/gcc/x86_64-redhat-linux/4.4.7/include/stddef.h"
typedef long int ptrdiff_t;

#line 211 "/usr/lib/gcc/x86_64-redhat-linux/4.4.7/include/stddef.h"
typedef unsigned long int size_t;

#line 43 "cannyx.sc"
typedef unsigned char img[4110080];
typedef short int simg[4110080];
typedef unsigned long long int time;

// class declarations ////////////////////////////////////////////////

#line 602 "cannyx.h"
class i_img_sender;

#line 47 "cannyx.sc"
/* note i_img_sender._SCE_STANDARD_LIB = { "i_sender","img","img" }; */

#line 608 "cannyx.h"
class i_img_receiver;

#line 48 "cannyx.sc"
/* note i_img_receiver._SCE_STANDARD_LIB = { "i_receiver","img","img" }; */

#line 614 "cannyx.h"
class i_img_tranceiver;

#line 49 "cannyx.sc"
/* note i_img_tranceiver._SCE_STANDARD_LIB = { "i_tranceiver","img","img" }; */

#line 620 "cannyx.h"
class c_img_queue;

#line 51 "cannyx.sc"
/* note c_img_queue._SCE_STANDARD_LIB = { "c_queue","img","img" }; */

#line 626 "cannyx.h"
class i_time_sender;

#line 53 "cannyx.sc"
/* note i_time_sender._SCE_STANDARD_LIB = { "i_sender","time","time" }; */

#line 632 "cannyx.h"
class i_time_receiver;

#line 54 "cannyx.sc"
/* note i_time_receiver._SCE_STANDARD_LIB = { "i_receiver","time","time" }; */

#line 638 "cannyx.h"
class i_time_tranceiver;

#line 55 "cannyx.sc"
/* note i_time_tranceiver._SCE_STANDARD_LIB = { "i_tranceiver","time","time" }; */

#line 644 "cannyx.h"
class c_time_queue;

#line 57 "cannyx.sc"
/* note c_time_queue._SCE_STANDARD_LIB = { "c_queue","time","time" }; */

#line 650 "cannyx.h"
class Stimulus;
class Monitor;
class DataIn;
class DataOut;
class Receive_Image;
class Gaussian_Kernel;
class BlurX_Slice;
class BlurX;
class BlurY_Slice;
class BlurY;
class Gaussian_Smooth;
class Derivative_X_Y;
class Magnitude_X_Y;
class Non_Max_Supp;
class Apply_Hysteresis;
class DUT;
class Platform;
class Main;

// interface class definitions ///////////////////////////////////////

#line 47 "cannyx.sc"
class i_img_sender
{
private:
public:

#line 678 "cannyx.h"
    virtual ~i_img_sender(void){};

#line 47 "cannyx.sc"
    virtual void send(unsigned char [4110080]) = 0;
private:
};

#line 48 "cannyx.sc"
class i_img_receiver
{
private:
public:

#line 692 "cannyx.h"
    virtual ~i_img_receiver(void){};

#line 48 "cannyx.sc"
    virtual void receive(unsigned char (*)[4110080]) = 0;
private:
};

#line 49 "cannyx.sc"
class i_img_tranceiver
{
private:
public:

#line 706 "cannyx.h"
    virtual ~i_img_tranceiver(void){};

#line 49 "cannyx.sc"
    virtual void receive(unsigned char (*)[4110080]) = 0; virtual void send(unsigned char [4110080]) = 0;
private:
};

class i_time_sender
{
private:
public:

#line 719 "cannyx.h"
    virtual ~i_time_sender(void){};

#line 53 "cannyx.sc"
    virtual void send(unsigned long long int) = 0;
private:
};

#line 54 "cannyx.sc"
class i_time_receiver
{
private:
public:

#line 733 "cannyx.h"
    virtual ~i_time_receiver(void){};

#line 54 "cannyx.sc"
    virtual void receive(unsigned long long int *) = 0;
private:
};

#line 55 "cannyx.sc"
class i_time_tranceiver
{
private:
public:

#line 747 "cannyx.h"
    virtual ~i_time_tranceiver(void){};

#line 55 "cannyx.sc"
    virtual void receive(unsigned long long int *) = 0; virtual void send(unsigned long long int) = 0;
private:
};

// behavior and channel class definitions ////////////////////////////

#line 51 "cannyx.sc"
class c_img_queue : public _specc::channel, public i_img_sender, public i_img_receiver, public i_img_tranceiver
{
private:

#line 51 "cannyx.sc"
    const unsigned long int (&size);
public:

#line 766 "cannyx.h"
    c_img_queue(const unsigned long int (&size));
    virtual ~c_img_queue(void);
    void cleanup(void);
    void receive(unsigned char (*)[4110080]);
    void send(unsigned char [4110080]);
    void setup(void);
private:

#line 51 "cannyx.sc"
    unsigned char (*buffer)[4110080]; unsigned long int n; unsigned long int p; _specc::event r; _specc::event s; unsigned long int wr; unsigned long int ws;
};




class c_time_queue : public _specc::channel, public i_time_sender, public i_time_receiver, public i_time_tranceiver
{
private:

#line 57 "cannyx.sc"
    const unsigned long int (&size);
public:

#line 790 "cannyx.h"
    c_time_queue(const unsigned long int (&size));
    virtual ~c_time_queue(void);
    void cleanup(void);
    void receive(unsigned long long int *);
    void send(unsigned long long int);
    void setup(void);
private:

#line 57 "cannyx.sc"
    unsigned long long int *buffer; unsigned long int n; unsigned long int p; _specc::event r; _specc::event s; unsigned long int wr; unsigned long int ws;
};
class Stimulus : public _specc::behavior
{
private:

#line 59 "cannyx.sc"
    i_img_sender (&ImgOut); i_time_sender (&TimeOut);
public:

#line 810 "cannyx.h"
    Stimulus(unsigned int _idcnt, i_img_sender (&ImgOut), i_time_sender (&TimeOut));
    virtual ~Stimulus(void);
    void main(void);
    int read_pgm_image(const char *, unsigned char *, int, int);
private:

#line 61 "cannyx.sc"
    unsigned char Image[4110080];

    char buffer[21];

#line 62 "cannyx.sc"
    unsigned long long int t;
};

#line 155 "cannyx.sc"
class Monitor : public _specc::behavior
{
private:

#line 155 "cannyx.sc"
    i_img_receiver (&ImgIn); i_time_receiver (&TimeIn);
public:

#line 835 "cannyx.h"
    Monitor(unsigned int _idcnt, i_img_receiver (&ImgIn), i_time_receiver (&TimeIn));
    virtual ~Monitor(void);
    void main(void);
    int write_pgm_image(const char *, unsigned char *, int, int, const char *, int);
private:

#line 157 "cannyx.sc"
    unsigned char EdgeImage[4110080];



    char buffer[21];

#line 160 "cannyx.sc"
    unsigned long long int d;

#line 158 "cannyx.sc"
    unsigned long long int t1;
    unsigned long long int t2;
};

#line 238 "cannyx.sc"
class DataIn : public _specc::behavior
{
private:

#line 238 "cannyx.sc"
    i_img_receiver (&ImgIn); i_img_sender (&ImgOut);
public:

#line 866 "cannyx.h"
    DataIn(unsigned int _idcnt, i_img_receiver (&ImgIn), i_img_sender (&ImgOut));
    virtual ~DataIn(void);
    void main();
private:

#line 240 "cannyx.sc"
    unsigned char Image[4110080];
};

#line 252 "cannyx.sc"
class DataOut : public _specc::behavior
{
private:

#line 252 "cannyx.sc"
    i_img_receiver (&ImgIn); i_img_sender (&ImgOut);
public:

#line 885 "cannyx.h"
    DataOut(unsigned int _idcnt, i_img_receiver (&ImgIn), i_img_sender (&ImgOut));
    virtual ~DataOut(void);
    void main();
private:

#line 254 "cannyx.sc"
    unsigned char Image[4110080];
};

#line 266 "cannyx.sc"
class Receive_Image : public _specc::behavior
{
private:

#line 266 "cannyx.sc"
    i_img_receiver (&ImgIn); unsigned char (&image)[4110080];
public:

#line 904 "cannyx.h"
    Receive_Image(unsigned int _idcnt, i_img_receiver (&ImgIn), unsigned char (&image)[4110080]);
    virtual ~Receive_Image(void);
    void main(void);
private:
};

#line 277 "cannyx.sc"
class Gaussian_Kernel : public _specc::behavior
{
private:

#line 277 "cannyx.sc"
    float (&gaussian_kernel)[21]; int (&kernel_center);
public:

#line 920 "cannyx.h"
    Gaussian_Kernel(unsigned int _idcnt, float (&gaussian_kernel)[21], int (&kernel_center));
    virtual ~Gaussian_Kernel(void);
    void main(void);
    void make_gaussian_kernel(float, float *, int *);
private:
};

#line 330 "cannyx.sc"
class BlurX_Slice : public _specc::behavior
{
private:

#line 330 "cannyx.sc"
    unsigned char (&image)[4110080]; float (&kernel)[21]; int (&center);
    float (&tempim)[4110080]; int (&XX);
public:

#line 938 "cannyx.h"
    BlurX_Slice(unsigned int _idcnt, unsigned char (&image)[4110080], float (&kernel)[21], int (&center), float (&tempim)[4110080], int (&XX));
    virtual ~BlurX_Slice(void);
    void blur_xs(int, int, int);
    void main(void);
private:
};

#line 366 "cannyx.sc"
class BlurX : public _specc::behavior
{
private:

#line 366 "cannyx.sc"
    unsigned char (&image)[4110080]; float (&kernel)[21]; int (&center);
    float (&tempim)[4110080]; float (&kernel1)[21]; int (&center1);
public:

#line 956 "cannyx.h"
    BlurX(unsigned int _idcnt, unsigned char (&image)[4110080], float (&kernel)[21], int (&center), float (&tempim)[4110080], float (&kernel1)[21], int (&center1));
    virtual ~BlurX(void);
    void main(void);
private:
    int _scc_const_port_0;
    int _scc_const_port_1;
    int _scc_const_port_2;
    int _scc_const_port_3;
    int _scc_const_port_4;
    int _scc_const_port_5;
    int _scc_const_port_6;
    int _scc_const_port_7;

#line 369 "cannyx.sc"
    BlurX_Slice X0;
    BlurX_Slice X1;
    BlurX_Slice X2;
    BlurX_Slice X3;
    BlurX_Slice X4;
    BlurX_Slice X5;
    BlurX_Slice X6;
    BlurX_Slice X7;
};

#line 386 "cannyx.sc"
class BlurY_Slice : public _specc::behavior
{
private:

#line 386 "cannyx.sc"
    float (&tempim)[4110080]; float (&kernel)[21]; int (&center);
    short int (&smoothedim)[4110080]; int (&XX);
public:

#line 991 "cannyx.h"
    BlurY_Slice(unsigned int _idcnt, float (&tempim)[4110080], float (&kernel)[21], int (&center), short int (&smoothedim)[4110080], int (&XX));
    virtual ~BlurY_Slice(void);
    void blur_ys(int, int, int);
    void main(void);
private:
};

#line 421 "cannyx.sc"
class BlurY : public _specc::behavior
{
private:

#line 421 "cannyx.sc"
    float (&tempim)[4110080]; float (&kernel)[21]; int (&center);
    short int (&smoothedim)[4110080];
public:

#line 1009 "cannyx.h"
    BlurY(unsigned int _idcnt, float (&tempim)[4110080], float (&kernel)[21], int (&center), short int (&smoothedim)[4110080]);
    virtual ~BlurY(void);
    void main(void);
private:
    int _scc_const_port_0;
    int _scc_const_port_1;
    int _scc_const_port_2;
    int _scc_const_port_3;
    int _scc_const_port_4;
    int _scc_const_port_5;
    int _scc_const_port_6;
    int _scc_const_port_7;

#line 424 "cannyx.sc"
    BlurY_Slice Y0;
    BlurY_Slice Y1;
    BlurY_Slice Y2;
    BlurY_Slice Y3;
    BlurY_Slice Y4;
    BlurY_Slice Y5;
    BlurY_Slice Y6;
    BlurY_Slice Y7;
};

#line 439 "cannyx.sc"
class Gaussian_Smooth : public _specc::behavior
{
private:

#line 439 "cannyx.sc"
    i_img_receiver (&ImgIn); unsigned char (&imageout)[4110080]; float (&kernelout)[21]; int (&centerout);
public:

#line 1043 "cannyx.h"
    Gaussian_Smooth(unsigned int _idcnt, i_img_receiver (&ImgIn), unsigned char (&imageout)[4110080], float (&kernelout)[21], int (&centerout));
    virtual ~Gaussian_Smooth(void);
    void main(void);
private:

#line 453 "cannyx.sc"
    Gaussian_Kernel gauss;

#line 452 "cannyx.sc"
    Receive_Image receive;
};

#line 468 "cannyx.sc"
class Derivative_X_Y : public _specc::behavior
{
private:

#line 468 "cannyx.sc"
    short int (&smoothedim)[4110080]; short int (&delta_x)[4110080]; short int (&delta_y)[4110080];
public:

#line 1065 "cannyx.h"
    Derivative_X_Y(unsigned int _idcnt, short int (&smoothedim)[4110080], short int (&delta_x)[4110080], short int (&delta_y)[4110080]);
    virtual ~Derivative_X_Y(void);
    void derivative_x_y(int, int);
    void main(void);
private:
};

#line 524 "cannyx.sc"
class Magnitude_X_Y : public _specc::behavior
{
private:

#line 524 "cannyx.sc"
    short int (&delta_x)[4110080]; short int (&delta_y)[4110080]; short int (&magnitude)[4110080]; short int (&delta_x1)[4110080]; short int (&delta_y1)[4110080];
public:

#line 1082 "cannyx.h"
    Magnitude_X_Y(unsigned int _idcnt, short int (&delta_x)[4110080], short int (&delta_y)[4110080], short int (&magnitude)[4110080], short int (&delta_x1)[4110080], short int (&delta_y1)[4110080]);
    virtual ~Magnitude_X_Y(void);
    void magnitude_x_y(int, int);
    void main(void);
private:
};

#line 555 "cannyx.sc"
class Non_Max_Supp : public _specc::behavior
{
private:

#line 555 "cannyx.sc"
    short int (&gradx)[4110080]; short int (&grady)[4110080]; short int (&mag)[4110080]; unsigned char (&nms)[4110080]; short int (&magx)[4110080];
public:

#line 1099 "cannyx.h"
    Non_Max_Supp(unsigned int _idcnt, short int (&gradx)[4110080], short int (&grady)[4110080], short int (&mag)[4110080], unsigned char (&nms)[4110080], short int (&magx)[4110080]);
    virtual ~Non_Max_Supp(void);
    void main(void);
    void non_max_supp(int, int, unsigned char *);
private:
};

#line 772 "cannyx.sc"
class Apply_Hysteresis : public _specc::behavior
{
private:

#line 772 "cannyx.sc"
    short int (&mag)[4110080]; unsigned char (&nms)[4110080]; i_img_sender (&ImgOut);
public:

#line 1116 "cannyx.h"
    Apply_Hysteresis(unsigned int _idcnt, short int (&mag)[4110080], unsigned char (&nms)[4110080], i_img_sender (&ImgOut));
    virtual ~Apply_Hysteresis(void);
    void apply_hysteresis(int, int, float, float, unsigned char *);
    void follow_edges(unsigned char *, short int *, short int, int);
    void main(void);
private:

#line 774 "cannyx.sc"
    unsigned char EdgeImage[4110080];
};

#line 918 "cannyx.sc"
class DUT : public _specc::behavior
{
private:

#line 918 "cannyx.sc"
    i_img_receiver (&ImgIn); i_img_sender (&ImgOut);
public:

#line 1137 "cannyx.h"
    DUT(unsigned int _idcnt, i_img_receiver (&ImgIn), i_img_sender (&ImgOut));
    virtual ~DUT(void);
    void main(void);
private:

#line 925 "cannyx.sc"
    _specc::piped<int,1> center;

#line 936 "cannyx.sc"
    _specc::piped<int,1> center1;

#line 922 "cannyx.sc"
    _specc::piped<short int [4110080],1> delta_x;

#line 938 "cannyx.sc"
    _specc::piped<short int [4110080],1> delta_x1;

#line 923 "cannyx.sc"
    _specc::piped<short int [4110080],1> delta_y;

#line 939 "cannyx.sc"
    _specc::piped<short int [4110080],1> delta_y1;

#line 927 "cannyx.sc"
    _specc::piped<unsigned char [4110080],1> image;

#line 926 "cannyx.sc"
    _specc::piped<float [21],1> kernel;

#line 937 "cannyx.sc"
    _specc::piped<float [21],1> kernel1;

#line 924 "cannyx.sc"
    _specc::piped<short int [4110080],1> magnitude;

#line 940 "cannyx.sc"
    _specc::piped<short int [4110080],1> magnitude1;

#line 920 "cannyx.sc"
    _specc::piped<unsigned char [4110080],1> nms;
    _specc::piped<short int [4110080],1> smoothedim;

#line 928 "cannyx.sc"
    _specc::piped<float [4110080],1> tempim;

#line 948 "cannyx.sc"
    Apply_Hysteresis apply_hysteresis;

#line 943 "cannyx.sc"
    BlurX blurX;
    BlurY blurY;
    Derivative_X_Y derivative_x_y;

#line 942 "cannyx.sc"
    Gaussian_Smooth gaussian_smooth;



    Magnitude_X_Y magnitude_x_y;
    Non_Max_Supp non_max_supp;
};

#line 994 "cannyx.sc"
class Platform : public _specc::behavior
{
private:

#line 994 "cannyx.sc"
    i_img_receiver (&ImgIn); i_img_sender (&ImgOut);
public:

#line 1209 "cannyx.h"
    Platform(unsigned int _idcnt, i_img_receiver (&ImgIn), i_img_sender (&ImgOut));
    virtual ~Platform(void);
    void main();
private:
    unsigned long int _scc_const_port_0;
    unsigned long int _scc_const_port_1;

#line 998 "cannyx.sc"
    DUT canny;

#line 997 "cannyx.sc"
    DataIn din;

    DataOut dout;

#line 996 "cannyx.sc"
    c_img_queue q1; c_img_queue q2;
};

#line 1012 "cannyx.sc"
class Main : public _specc::class_type
{
private:
public:

#line 1235 "cannyx.h"
    Main(unsigned int _idcnt);
    virtual ~Main(void);
    int main(void);
private:
    unsigned long int _scc_const_port_0;
    unsigned long int _scc_const_port_1;
    unsigned long int _scc_const_port_2;

#line 1015 "cannyx.sc"
    c_time_queue T;


    Monitor monitor;

#line 1017 "cannyx.sc"
    Platform platform;

#line 1014 "cannyx.sc"
    c_img_queue q1; c_img_queue q2;

    Stimulus stimulus;
};

// variable and function declarations ////////////////////////////////

#line 49 "/opt/sce/inc/sim.sh"
extern const int _SPECC_VERSION_MAJOR;
extern const int _SPECC_VERSION_MINOR;

#line 42 "/opt/sce/inc/sim/bit.sh"
extern "C" char *bit2str(unsigned int, char *, ...);

#line 48 "/opt/sce/inc/sim/bit.sh"
extern "C" char *ubit2str(unsigned int, char *, ...);




extern "C" void str2bit(unsigned int, const char *, ...);




extern "C" void str2ubit(unsigned int, const char *, ...);

#line 41 "/opt/sce/inc/sim/longlong.sh"
extern "C" char *ll2str(unsigned int, char *, long long int);




extern "C" char *ull2str(unsigned int, char *, unsigned long long int);




extern "C" long long int str2ll(unsigned int, const char *);



extern "C" unsigned long long int str2ull(unsigned int, const char *);

#line 71 "/opt/sce/inc/sim/sim.sh"
extern "C" unsigned long long int thread_id(void);

extern "C" void sim_exit(int);

#line 73 "/opt/sce/inc/sim/time.sh"
extern "C" unsigned long long int now(void);

extern "C" unsigned long long int delta(void);


extern "C" const char *time2str(char [21], unsigned long long int);



extern "C" unsigned long long int str2time(const char *);

#line 33 "/usr/include/alloca.h"
extern "C" void *alloca(unsigned long int);

#line 55 "/usr/include/bits/mathcalls.h"
extern "C" double __acos(double); extern "C" float __acosf(float); extern "C" long double __acosl(long double); extern "C" double acos(double); extern "C" float acosf(float); extern "C" long double acosl(long double);

extern "C" double __asin(double); extern "C" float __asinf(float); extern "C" long double __asinl(long double); extern "C" double asin(double); extern "C" float asinf(float); extern "C" long double asinl(long double);

extern "C" double __atan(double); extern "C" float __atanf(float); extern "C" long double __atanl(long double); extern "C" double atan(double); extern "C" float atanf(float); extern "C" long double atanl(long double);

extern "C" double __atan2(double, double); extern "C" float __atan2f(float, float); extern "C" long double __atan2l(long double, long double); extern "C" double atan2(double, double); extern "C" float atan2f(float, float); extern "C" long double atan2l(long double, long double);


extern "C" double __cos(double); extern "C" float __cosf(float); extern "C" long double __cosl(long double); extern "C" double cos(double); extern "C" float cosf(float); extern "C" long double cosl(long double);

extern "C" double __sin(double); extern "C" float __sinf(float); extern "C" long double __sinl(long double); extern "C" double sin(double); extern "C" float sinf(float); extern "C" long double sinl(long double);

extern "C" double __tan(double); extern "C" float __tanf(float); extern "C" long double __tanl(long double); extern "C" double tan(double); extern "C" float tanf(float); extern "C" long double tanl(long double);




extern "C" double __cosh(double); extern "C" float __coshf(float); extern "C" long double __coshl(long double); extern "C" double cosh(double); extern "C" float coshf(float); extern "C" long double coshl(long double);

extern "C" double __sinh(double); extern "C" float __sinhf(float); extern "C" long double __sinhl(long double); extern "C" double sinh(double); extern "C" float sinhf(float); extern "C" long double sinhl(long double);

extern "C" double __tanh(double); extern "C" float __tanhf(float); extern "C" long double __tanhl(long double); extern "C" double tanh(double); extern "C" float tanhf(float); extern "C" long double tanhl(long double);

#line 89 "/usr/include/bits/mathcalls.h"
extern "C" double __acosh(double); extern "C" float __acoshf(float); extern "C" long double __acoshl(long double); extern "C" double acosh(double); extern "C" float acoshf(float); extern "C" long double acoshl(long double);

extern "C" double __asinh(double); extern "C" float __asinhf(float); extern "C" long double __asinhl(long double); extern "C" double asinh(double); extern "C" float asinhf(float); extern "C" long double asinhl(long double);

extern "C" double __atanh(double); extern "C" float __atanhf(float); extern "C" long double __atanhl(long double); extern "C" double atanh(double); extern "C" float atanhf(float); extern "C" long double atanhl(long double);

#line 101 "/usr/include/bits/mathcalls.h"
extern "C" double __exp(double); extern "C" float __expf(float); extern "C" long double __expl(long double); extern "C" double exp(double); extern "C" float expf(float); extern "C" long double expl(long double);


extern "C" double __frexp(double, int *); extern "C" float __frexpf(float, int *); extern "C" long double __frexpl(long double, int *); extern "C" double frexp(double, int *); extern "C" float frexpf(float, int *); extern "C" long double frexpl(long double, int *);


extern "C" double __ldexp(double, int); extern "C" float __ldexpf(float, int); extern "C" long double __ldexpl(long double, int); extern "C" double ldexp(double, int); extern "C" float ldexpf(float, int); extern "C" long double ldexpl(long double, int);


extern "C" double __log(double); extern "C" float __logf(float); extern "C" long double __logl(long double); extern "C" double log(double); extern "C" float logf(float); extern "C" long double logl(long double);


extern "C" double __log10(double); extern "C" float __log10f(float); extern "C" long double __log10l(long double); extern "C" double log10(double); extern "C" float log10f(float); extern "C" long double log10l(long double);


extern "C" double __modf(double, double *); extern "C" float __modff(float, float *); extern "C" long double __modfl(long double, long double *); extern "C" double modf(double, double *); extern "C" float modff(float, float *); extern "C" long double modfl(long double, long double *);

#line 129 "/usr/include/bits/mathcalls.h"
extern "C" double __expm1(double); extern "C" float __expm1f(float); extern "C" long double __expm1l(long double); extern "C" double expm1(double); extern "C" float expm1f(float); extern "C" long double expm1l(long double);


extern "C" double __log1p(double); extern "C" float __log1pf(float); extern "C" long double __log1pl(long double); extern "C" double log1p(double); extern "C" float log1pf(float); extern "C" long double log1pl(long double);


extern "C" double __logb(double); extern "C" float __logbf(float); extern "C" long double __logbl(long double); extern "C" double logb(double); extern "C" float logbf(float); extern "C" long double logbl(long double);

#line 142 "/usr/include/bits/mathcalls.h"
extern "C" double __exp2(double); extern "C" float __exp2f(float); extern "C" long double __exp2l(long double); extern "C" double exp2(double); extern "C" float exp2f(float); extern "C" long double exp2l(long double);


extern "C" double __log2(double); extern "C" float __log2f(float); extern "C" long double __log2l(long double); extern "C" double log2(double); extern "C" float log2f(float); extern "C" long double log2l(long double);

#line 154 "/usr/include/bits/mathcalls.h"
extern "C" double __pow(double, double); extern "C" float __powf(float, float); extern "C" long double __powl(long double, long double); extern "C" double pow(double, double); extern "C" float powf(float, float); extern "C" long double powl(long double, long double);


extern "C" double __sqrt(double); extern "C" float __sqrtf(float); extern "C" long double __sqrtl(long double); extern "C" double sqrt(double); extern "C" float sqrtf(float); extern "C" long double sqrtl(long double);

#line 163 "/usr/include/bits/mathcalls.h"
extern "C" double __hypot(double, double); extern "C" float __hypotf(float, float); extern "C" long double __hypotl(long double, long double); extern "C" double hypot(double, double); extern "C" float hypotf(float, float); extern "C" long double hypotl(long double, long double);

#line 170 "/usr/include/bits/mathcalls.h"
extern "C" double __cbrt(double); extern "C" float __cbrtf(float); extern "C" long double __cbrtl(long double); extern "C" double cbrt(double); extern "C" float cbrtf(float); extern "C" long double cbrtl(long double);

#line 179 "/usr/include/bits/mathcalls.h"
extern "C" double __ceil(double); extern "C" float __ceilf(float); extern "C" long double __ceill(long double); extern "C" double ceil(double); extern "C" float ceilf(float); extern "C" long double ceill(long double);


extern "C" double __fabs(double); extern "C" float __fabsf(float); extern "C" long double __fabsl(long double); extern "C" double fabs(double); extern "C" float fabsf(float); extern "C" long double fabsl(long double);


extern "C" double __floor(double); extern "C" float __floorf(float); extern "C" long double __floorl(long double); extern "C" double floor(double); extern "C" float floorf(float); extern "C" long double floorl(long double);


extern "C" double __fmod(double, double); extern "C" float __fmodf(float, float); extern "C" long double __fmodl(long double, long double); extern "C" double fmod(double, double); extern "C" float fmodf(float, float); extern "C" long double fmodl(long double, long double);




extern "C" int __isinf(double); extern "C" int __isinff(float); extern "C" int __isinfl(long double);


extern "C" int __finite(double); extern "C" int __finitef(float); extern "C" int __finitel(long double);

#line 202 "/usr/include/bits/mathcalls.h"
extern "C" int isinf(double); extern "C" int isinff(float); extern "C" int isinfl(long double);


extern "C" int finite(double); extern "C" int finitef(float); extern "C" int finitel(long double);


extern "C" double __drem(double, double); extern "C" float __dremf(float, float); extern "C" long double __dreml(long double, long double); extern "C" double drem(double, double); extern "C" float dremf(float, float); extern "C" long double dreml(long double, long double);



extern "C" double __significand(double); extern "C" float __significandf(float); extern "C" long double __significandl(long double); extern "C" double significand(double); extern "C" float significandf(float); extern "C" long double significandl(long double);

#line 218 "/usr/include/bits/mathcalls.h"
extern "C" double __copysign(double, double); extern "C" float __copysignf(float, float); extern "C" long double __copysignl(long double, long double); extern "C" double copysign(double, double); extern "C" float copysignf(float, float); extern "C" long double copysignl(long double, long double);

#line 225 "/usr/include/bits/mathcalls.h"
extern "C" double __nan(const char *); extern "C" float __nanf(const char *); extern "C" long double __nanl(const char *); extern "C" double nan(const char *); extern "C" float nanf(const char *); extern "C" long double nanl(const char *);

#line 231 "/usr/include/bits/mathcalls.h"
extern "C" int __isnan(double); extern "C" int __isnanf(float); extern "C" int __isnanl(long double);



extern "C" int isnan(double); extern "C" int isnanf(float); extern "C" int isnanl(long double);


extern "C" double __j0(double); extern "C" float __j0f(float); extern "C" long double __j0l(long double); extern "C" double j0(double); extern "C" float j0f(float); extern "C" long double j0l(long double);
extern "C" double __j1(double); extern "C" float __j1f(float); extern "C" long double __j1l(long double); extern "C" double j1(double); extern "C" float j1f(float); extern "C" long double j1l(long double);
extern "C" double __jn(int, double); extern "C" float __jnf(int, float); extern "C" long double __jnl(int, long double); extern "C" double jn(int, double); extern "C" float jnf(int, float); extern "C" long double jnl(int, long double);
extern "C" double __y0(double); extern "C" float __y0f(float); extern "C" long double __y0l(long double); extern "C" double y0(double); extern "C" float y0f(float); extern "C" long double y0l(long double);
extern "C" double __y1(double); extern "C" float __y1f(float); extern "C" long double __y1l(long double); extern "C" double y1(double); extern "C" float y1f(float); extern "C" long double y1l(long double);
extern "C" double __yn(int, double); extern "C" float __ynf(int, float); extern "C" long double __ynl(int, long double); extern "C" double yn(int, double); extern "C" float ynf(int, float); extern "C" long double ynl(int, long double);

#line 250 "/usr/include/bits/mathcalls.h"
extern "C" double __erf(double); extern "C" float __erff(float); extern "C" long double __erfl(long double); extern "C" double erf(double); extern "C" float erff(float); extern "C" long double erfl(long double);
extern "C" double __erfc(double); extern "C" float __erfcf(float); extern "C" long double __erfcl(long double); extern "C" double erfc(double); extern "C" float erfcf(float); extern "C" long double erfcl(long double);
extern "C" double __lgamma(double); extern "C" float __lgammaf(float); extern "C" long double __lgammal(long double); extern "C" double lgamma(double); extern "C" float lgammaf(float); extern "C" long double lgammal(long double);

#line 259 "/usr/include/bits/mathcalls.h"
extern "C" double __tgamma(double); extern "C" float __tgammaf(float); extern "C" long double __tgammal(long double); extern "C" double tgamma(double); extern "C" float tgammaf(float); extern "C" long double tgammal(long double);

#line 265 "/usr/include/bits/mathcalls.h"
extern "C" double __gamma(double); extern "C" float __gammaf(float); extern "C" long double __gammal(long double); extern "C" double gamma(double); extern "C" float gammaf(float); extern "C" long double gammal(long double);

#line 272 "/usr/include/bits/mathcalls.h"
extern "C" double __lgamma_r(double, int *); extern "C" float __lgammaf_r(float, int *); extern "C" long double __lgammal_r(long double, int *); extern "C" double lgamma_r(double, int *); extern "C" float lgammaf_r(float, int *); extern "C" long double lgammal_r(long double, int *);

#line 280 "/usr/include/bits/mathcalls.h"
extern "C" double __rint(double); extern "C" float __rintf(float); extern "C" long double __rintl(long double); extern "C" double rint(double); extern "C" float rintf(float); extern "C" long double rintl(long double);


extern "C" double __nextafter(double, double); extern "C" float __nextafterf(float, float); extern "C" long double __nextafterl(long double, long double); extern "C" double nextafter(double, double); extern "C" float nextafterf(float, float); extern "C" long double nextafterl(long double, long double);

extern "C" double __nexttoward(double, long double); extern "C" float __nexttowardf(float, long double); extern "C" long double __nexttowardl(long double, long double); extern "C" double nexttoward(double, long double); extern "C" float nexttowardf(float, long double); extern "C" long double nexttowardl(long double, long double);



extern "C" double __remainder(double, double); extern "C" float __remainderf(float, float); extern "C" long double __remainderl(long double, long double); extern "C" double remainder(double, double); extern "C" float remainderf(float, float); extern "C" long double remainderl(long double, long double);



extern "C" double __scalbn(double, int); extern "C" float __scalbnf(float, int); extern "C" long double __scalbnl(long double, int); extern "C" double scalbn(double, int); extern "C" float scalbnf(float, int); extern "C" long double scalbnl(long double, int);



extern "C" int __ilogb(double); extern "C" int __ilogbf(float); extern "C" int __ilogbl(long double); extern "C" int ilogb(double); extern "C" int ilogbf(float); extern "C" int ilogbl(long double);




extern "C" double __scalbln(double, long int); extern "C" float __scalblnf(float, long int); extern "C" long double __scalblnl(long double, long int); extern "C" double scalbln(double, long int); extern "C" float scalblnf(float, long int); extern "C" long double scalblnl(long double, long int);



extern "C" double __nearbyint(double); extern "C" float __nearbyintf(float); extern "C" long double __nearbyintl(long double); extern "C" double nearbyint(double); extern "C" float nearbyintf(float); extern "C" long double nearbyintl(long double);



extern "C" double __round(double); extern "C" float __roundf(float); extern "C" long double __roundl(long double); extern "C" double round(double); extern "C" float roundf(float); extern "C" long double roundl(long double);



extern "C" double __trunc(double); extern "C" float __truncf(float); extern "C" long double __truncl(long double); extern "C" double trunc(double); extern "C" float truncf(float); extern "C" long double truncl(long double);




extern "C" double __remquo(double, double, int *); extern "C" float __remquof(float, float, int *); extern "C" long double __remquol(long double, long double, int *); extern "C" double remquo(double, double, int *); extern "C" float remquof(float, float, int *); extern "C" long double remquol(long double, long double, int *);

#line 326 "/usr/include/bits/mathcalls.h"
extern "C" long int __lrint(double); extern "C" long int __lrintf(float); extern "C" long int __lrintl(long double); extern "C" long int lrint(double); extern "C" long int lrintf(float); extern "C" long int lrintl(long double);
extern "C" long long int __llrint(double); extern "C" long long int __llrintf(float); extern "C" long long int __llrintl(long double); extern "C" long long int llrint(double); extern "C" long long int llrintf(float); extern "C" long long int llrintl(long double);



extern "C" long int __lround(double); extern "C" long int __lroundf(float); extern "C" long int __lroundl(long double); extern "C" long int lround(double); extern "C" long int lroundf(float); extern "C" long int lroundl(long double);
extern "C" long long int __llround(double); extern "C" long long int __llroundf(float); extern "C" long long int __llroundl(long double); extern "C" long long int llround(double); extern "C" long long int llroundf(float); extern "C" long long int llroundl(long double);



extern "C" double __fdim(double, double); extern "C" float __fdimf(float, float); extern "C" long double __fdiml(long double, long double); extern "C" double fdim(double, double); extern "C" float fdimf(float, float); extern "C" long double fdiml(long double, long double);


extern "C" double __fmax(double, double); extern "C" float __fmaxf(float, float); extern "C" long double __fmaxl(long double, long double); extern "C" double fmax(double, double); extern "C" float fmaxf(float, float); extern "C" long double fmaxl(long double, long double);


extern "C" double __fmin(double, double); extern "C" float __fminf(float, float); extern "C" long double __fminl(long double, long double); extern "C" double fmin(double, double); extern "C" float fminf(float, float); extern "C" long double fminl(long double, long double);



extern "C" int __fpclassify(double); extern "C" int __fpclassifyf(float); extern "C" int __fpclassifyl(long double);



extern "C" int __signbit(double); extern "C" int __signbitf(float); extern "C" int __signbitl(long double);




extern "C" double __fma(double, double, double); extern "C" float __fmaf(float, float, float); extern "C" long double __fmal(long double, long double, long double); extern "C" double fma(double, double, double); extern "C" float fmaf(float, float, float); extern "C" long double fmal(long double, long double, long double);

#line 364 "/usr/include/bits/mathcalls.h"
extern "C" double __scalb(double, double); extern "C" float __scalbf(float, float); extern "C" long double __scalbl(long double, long double); extern "C" double scalb(double, double); extern "C" float scalbf(float, float); extern "C" long double scalbl(long double, long double);

#line 27 "/usr/include/bits/sys_errlist.h"
extern int sys_nerr;
extern const char *const sys_errlist[];

#line 346 "/usr/include/libio.h"
extern struct _IO_FILE_plus _IO_2_1_stdin_;
extern struct _IO_FILE_plus _IO_2_1_stdout_;
extern struct _IO_FILE_plus _IO_2_1_stderr_;

#line 416 "/usr/include/libio.h"
extern "C" int __underflow(struct _IO_FILE *);
extern "C" int __uflow(struct _IO_FILE *);
extern "C" int __overflow(struct _IO_FILE *, int);

#line 460 "/usr/include/libio.h"
extern "C" int _IO_getc(struct _IO_FILE *);
extern "C" int _IO_putc(int, struct _IO_FILE *);
extern "C" int _IO_feof(struct _IO_FILE *);
extern "C" int _IO_ferror(struct _IO_FILE *);

extern "C" int _IO_peekc_locked(struct _IO_FILE *);

#line 471 "/usr/include/libio.h"
extern "C" void _IO_flockfile(struct _IO_FILE *);
extern "C" void _IO_funlockfile(struct _IO_FILE *);
extern "C" int _IO_ftrylockfile(struct _IO_FILE *);

#line 490 "/usr/include/libio.h"
extern "C" int _IO_vfscanf(struct _IO_FILE *, const char *, void *, int *);

extern "C" int _IO_vfprintf(struct _IO_FILE *, const char *, void *);

extern "C" long int _IO_padn(struct _IO_FILE *, int, long int);
extern "C" unsigned long int _IO_sgetn(struct _IO_FILE *, void *, unsigned long int);

extern "C" long int _IO_seekoff(struct _IO_FILE *, long int, int, int);
extern "C" long int _IO_seekpos(struct _IO_FILE *, long int, int);

extern "C" void _IO_free_backup_area(struct _IO_FILE *);

#line 157 "/usr/include/math.h"
extern int signgam;

#line 303 "/usr/include/math.h"
extern _LIB_VERSION_TYPE _LIB_VERSION;

#line 329 "/usr/include/math.h"
extern "C" int matherr(struct exception *);

#line 165 "/usr/include/stdio.h"
extern struct _IO_FILE *stdin;
extern struct _IO_FILE *stdout;
extern struct _IO_FILE *stderr;

#line 177 "/usr/include/stdio.h"
extern "C" int remove(const char *);

extern "C" int rename(const char *, const char *);

#line 194 "/usr/include/stdio.h"
extern "C" struct _IO_FILE *tmpfile(void);

#line 208 "/usr/include/stdio.h"
extern "C" char *tmpnam(char *);

#line 214 "/usr/include/stdio.h"
extern "C" char *tmpnam_r(char *);

#line 226 "/usr/include/stdio.h"
extern "C" char *tempnam(const char *, const char *);

#line 236 "/usr/include/stdio.h"
extern "C" int fclose(struct _IO_FILE *);




extern "C" int fflush(struct _IO_FILE *);

#line 251 "/usr/include/stdio.h"
extern "C" int fflush_unlocked(struct _IO_FILE *);

#line 271 "/usr/include/stdio.h"
extern "C" struct _IO_FILE *fopen(const char *, const char *);

#line 277 "/usr/include/stdio.h"
extern "C" struct _IO_FILE *freopen(const char *, const char *, struct _IO_FILE *);

#line 305 "/usr/include/stdio.h"
extern "C" struct _IO_FILE *fdopen(int, const char *);

#line 331 "/usr/include/stdio.h"
extern "C" void setbuf(struct _IO_FILE *, char *);



extern "C" int setvbuf(struct _IO_FILE *, char *, int, unsigned long int);

#line 342 "/usr/include/stdio.h"
extern "C" void setbuffer(struct _IO_FILE *, char *, unsigned long int);



extern "C" void setlinebuf(struct _IO_FILE *);

#line 355 "/usr/include/stdio.h"
extern "C" int fprintf(struct _IO_FILE *, const char *, ...);

#line 361 "/usr/include/stdio.h"
extern "C" int printf(const char *, ...);

extern "C" int sprintf(char *, const char *, ...);

#line 370 "/usr/include/stdio.h"
extern "C" int vfprintf(struct _IO_FILE *, const char *, void *);

#line 376 "/usr/include/stdio.h"
extern "C" int vprintf(const char *, void *);

extern "C" int vsprintf(char *, const char *, void *);

#line 385 "/usr/include/stdio.h"
extern "C" int snprintf(char *, unsigned long int, const char *, ...);



extern "C" int vsnprintf(char *, unsigned long int, const char *, void *);

#line 429 "/usr/include/stdio.h"
extern "C" int fscanf(struct _IO_FILE *, const char *, ...);

#line 435 "/usr/include/stdio.h"
extern "C" int scanf(const char *, ...);

extern "C" int sscanf(const char *, const char *, ...);

#line 456 "/usr/include/stdio.h"
extern "C" int __isoc99_fscanf(struct _IO_FILE *, const char *, ...);

extern "C" int __isoc99_scanf(const char *, ...);
extern "C" int __isoc99_sscanf(const char *, const char *, ...);

#line 475 "/usr/include/stdio.h"
extern "C" int vfscanf(struct _IO_FILE *, const char *, void *);

#line 483 "/usr/include/stdio.h"
extern "C" int vscanf(const char *, void *);



extern "C" int vsscanf(const char *, const char *, void *);

#line 512 "/usr/include/stdio.h"
extern "C" int __isoc99_vfscanf(struct _IO_FILE *, const char *, void *);


extern "C" int __isoc99_vscanf(const char *, void *);

extern "C" int __isoc99_vsscanf(const char *, const char *, void *);

#line 535 "/usr/include/stdio.h"
extern "C" int fgetc(struct _IO_FILE *);
extern "C" int getc(struct _IO_FILE *);

#line 542 "/usr/include/stdio.h"
extern "C" int getchar(void);

#line 554 "/usr/include/stdio.h"
extern "C" int getc_unlocked(struct _IO_FILE *);
extern "C" int getchar_unlocked(void);

#line 565 "/usr/include/stdio.h"
extern "C" int fgetc_unlocked(struct _IO_FILE *);

#line 577 "/usr/include/stdio.h"
extern "C" int fputc(int, struct _IO_FILE *);
extern "C" int putc(int, struct _IO_FILE *);

#line 584 "/usr/include/stdio.h"
extern "C" int putchar(int);

#line 598 "/usr/include/stdio.h"
extern "C" int fputc_unlocked(int, struct _IO_FILE *);

#line 606 "/usr/include/stdio.h"
extern "C" int putc_unlocked(int, struct _IO_FILE *);
extern "C" int putchar_unlocked(int);

#line 614 "/usr/include/stdio.h"
extern "C" int getw(struct _IO_FILE *);


extern "C" int putw(int, struct _IO_FILE *);

#line 626 "/usr/include/stdio.h"
extern "C" char *fgets(char *, int, struct _IO_FILE *);

#line 634 "/usr/include/stdio.h"
extern "C" char *gets(char *);

#line 684 "/usr/include/stdio.h"
extern "C" int fputs(const char *, struct _IO_FILE *);

#line 690 "/usr/include/stdio.h"
extern "C" int puts(const char *);

#line 697 "/usr/include/stdio.h"
extern "C" int ungetc(int, struct _IO_FILE *);

#line 704 "/usr/include/stdio.h"
extern "C" unsigned long int fread(void *, unsigned long int, unsigned long int, struct _IO_FILE *);

#line 710 "/usr/include/stdio.h"
extern "C" unsigned long int fwrite(const void *, unsigned long int, unsigned long int, struct _IO_FILE *);

#line 732 "/usr/include/stdio.h"
extern "C" unsigned long int fread_unlocked(void *, unsigned long int, unsigned long int, struct _IO_FILE *);

extern "C" unsigned long int fwrite_unlocked(const void *, unsigned long int, unsigned long int, struct _IO_FILE *);

#line 744 "/usr/include/stdio.h"
extern "C" int fseek(struct _IO_FILE *, long int, int);




extern "C" long int ftell(struct _IO_FILE *);




extern "C" void rewind(struct _IO_FILE *);

#line 768 "/usr/include/stdio.h"
extern "C" int fseeko(struct _IO_FILE *, long int, int);




extern "C" long int ftello(struct _IO_FILE *);

#line 793 "/usr/include/stdio.h"
extern "C" int fgetpos(struct _IO_FILE *, _G_fpos_t *);




extern "C" int fsetpos(struct _IO_FILE *, const _G_fpos_t *);

#line 821 "/usr/include/stdio.h"
extern "C" void clearerr(struct _IO_FILE *);

extern "C" int feof(struct _IO_FILE *);

extern "C" int ferror(struct _IO_FILE *);




extern "C" void clearerr_unlocked(struct _IO_FILE *);
extern "C" int feof_unlocked(struct _IO_FILE *);
extern "C" int ferror_unlocked(struct _IO_FILE *);

#line 841 "/usr/include/stdio.h"
extern "C" void perror(const char *);

#line 853 "/usr/include/stdio.h"
extern "C" int fileno(struct _IO_FILE *);




extern "C" int fileno_unlocked(struct _IO_FILE *);

#line 868 "/usr/include/stdio.h"
extern "C" struct _IO_FILE *popen(const char *, const char *);

#line 874 "/usr/include/stdio.h"
extern "C" int pclose(struct _IO_FILE *);

#line 880 "/usr/include/stdio.h"
extern "C" char *ctermid(char *);

#line 908 "/usr/include/stdio.h"
extern "C" void flockfile(struct _IO_FILE *);



extern "C" int ftrylockfile(struct _IO_FILE *);


extern "C" void funlockfile(struct _IO_FILE *);

#line 140 "/usr/include/stdlib.h"
extern "C" unsigned long int __ctype_get_mb_cur_max(void);




extern "C" double atof(const char *);


extern "C" int atoi(const char *);


extern "C" long int atol(const char *);

#line 158 "/usr/include/stdlib.h"
extern "C" long long int atoll(const char *);

#line 165 "/usr/include/stdlib.h"
extern "C" double strtod(const char *, char **);

#line 173 "/usr/include/stdlib.h"
extern "C" float strtof(const char *, char **);


extern "C" long double strtold(const char *, char **);

#line 184 "/usr/include/stdlib.h"
extern "C" long int strtol(const char *, char **, int);



extern "C" unsigned long int strtoul(const char *, char **, int);

#line 210 "/usr/include/stdlib.h"
extern "C" long long int strtoll(const char *, char **, int);




extern "C" unsigned long long int strtoull(const char *, char **, int);

#line 311 "/usr/include/stdlib.h"
extern "C" char *l64a(long int);


extern "C" long int a64l(const char *);

#line 327 "/usr/include/stdlib.h"
extern "C" long int random(void);


extern "C" void srandom(unsigned int);

#line 336 "/usr/include/stdlib.h"
extern "C" char *initstate(unsigned int, char *, unsigned long int);




extern "C" char *setstate(char *);

#line 360 "/usr/include/stdlib.h"
extern "C" int random_r(struct random_data *, int *);


extern "C" int srandom_r(unsigned int, struct random_data *);


extern "C" int initstate_r(unsigned int, char *, unsigned long int, struct random_data *);




extern "C" int setstate_r(char *, struct random_data *);

#line 380 "/usr/include/stdlib.h"
extern "C" int rand(void);

extern "C" void srand(unsigned int);




extern "C" int rand_r(unsigned int *);

#line 395 "/usr/include/stdlib.h"
extern "C" double drand48(void);
extern "C" double erand48(unsigned short int [3]);


extern "C" long int lrand48(void);
extern "C" long int nrand48(unsigned short int [3]);



extern "C" long int mrand48(void);
extern "C" long int jrand48(unsigned short int [3]);



extern "C" void srand48(long int);
extern "C" unsigned short int *seed48(unsigned short int [3]);

extern "C" void lcong48(unsigned short int [7]);

#line 428 "/usr/include/stdlib.h"
extern "C" int drand48_r(struct drand48_data *, double *);

extern "C" int erand48_r(unsigned short int [3], struct drand48_data *, double *);




extern "C" int lrand48_r(struct drand48_data *, long int *);


extern "C" int nrand48_r(unsigned short int [3], struct drand48_data *, long int *);

#line 444 "/usr/include/stdlib.h"
extern "C" int mrand48_r(struct drand48_data *, long int *);


extern "C" int jrand48_r(unsigned short int [3], struct drand48_data *, long int *);

#line 453 "/usr/include/stdlib.h"
extern "C" int srand48_r(long int, struct drand48_data *);


extern "C" int seed48_r(unsigned short int [3], struct drand48_data *);


extern "C" int lcong48_r(unsigned short int [7], struct drand48_data *);

#line 471 "/usr/include/stdlib.h"
extern "C" void *malloc(unsigned long int);

extern "C" void *calloc(unsigned long int, unsigned long int);

#line 485 "/usr/include/stdlib.h"
extern "C" void *realloc(void *, unsigned long int);


extern "C" void free(void *);




extern "C" void cfree(void *);

#line 503 "/usr/include/stdlib.h"
extern "C" void *valloc(unsigned long int);




extern "C" int posix_memalign(void **, unsigned long int, unsigned long int);

#line 514 "/usr/include/stdlib.h"
extern "C" void abort(void);



extern "C" int atexit(void (*)(void));

#line 536 "/usr/include/stdlib.h"
extern "C" int on_exit(void (*)(int, void *), void *);

#line 544 "/usr/include/stdlib.h"
extern "C" void exit(int);

#line 560 "/usr/include/stdlib.h"
extern "C" void _Exit(int);

#line 567 "/usr/include/stdlib.h"
extern "C" char *getenv(const char *);




extern "C" char *__secure_getenv(const char *);

#line 579 "/usr/include/stdlib.h"
extern "C" int putenv(char *);

#line 585 "/usr/include/stdlib.h"
extern "C" int setenv(const char *, const char *, int);



extern "C" int unsetenv(const char *);

#line 596 "/usr/include/stdlib.h"
extern "C" int clearenv(void);

#line 606 "/usr/include/stdlib.h"
extern "C" char *mktemp(char *);

#line 620 "/usr/include/stdlib.h"
extern "C" int mkstemp(char *);

#line 642 "/usr/include/stdlib.h"
extern "C" int mkstemps(char *, int);

#line 663 "/usr/include/stdlib.h"
extern "C" char *mkdtemp(char *);

#line 717 "/usr/include/stdlib.h"
extern "C" int system(const char *);

#line 734 "/usr/include/stdlib.h"
extern "C" char *realpath(const char *, char *);

#line 755 "/usr/include/stdlib.h"
extern "C" void *bsearch(const void *, const void *, unsigned long int, unsigned long int, int (*)(const void *, const void *));

#line 761 "/usr/include/stdlib.h"
extern "C" void qsort(void *, unsigned long int, unsigned long int, int (*)(const void *, const void *));

#line 771 "/usr/include/stdlib.h"
extern "C" int abs(int);
extern "C" long int labs(long int);



extern "C" long long int llabs(long long int);

#line 785 "/usr/include/stdlib.h"
extern "C" div_t div(int, int);

extern "C" ldiv_t ldiv(long int, long int);

#line 793 "/usr/include/stdlib.h"
extern "C" lldiv_t lldiv(long long int, long long int);

#line 808 "/usr/include/stdlib.h"
extern "C" char *ecvt(double, int, int *, int *);

#line 814 "/usr/include/stdlib.h"
extern "C" char *fcvt(double, int, int *, int *);

#line 820 "/usr/include/stdlib.h"
extern "C" char *gcvt(double, int, char *);

#line 826 "/usr/include/stdlib.h"
extern "C" char *qecvt(long double, int, int *, int *);


extern "C" char *qfcvt(long double, int, int *, int *);


extern "C" char *qgcvt(long double, int, char *);

#line 838 "/usr/include/stdlib.h"
extern "C" int ecvt_r(double, int, int *, int *, char *, unsigned long int);


extern "C" int fcvt_r(double, int, int *, int *, char *, unsigned long int);



extern "C" int qecvt_r(long double, int, int *, int *, char *, unsigned long int);



extern "C" int qfcvt_r(long double, int, int *, int *, char *, unsigned long int);

#line 860 "/usr/include/stdlib.h"
extern "C" int mblen(const char *, unsigned long int);


extern "C" int mbtowc(int *, const char *, unsigned long int);



extern "C" int wctomb(char *, int);



extern "C" unsigned long int mbstowcs(int *, const char *, unsigned long int);


extern "C" unsigned long int wcstombs(char *, const int *, unsigned long int);

#line 885 "/usr/include/stdlib.h"
extern "C" int rpmatch(const char *);

#line 948 "/usr/include/stdlib.h"
extern "C" int getloadavg(double [], int);

#line 44 "/usr/include/string.h"
extern "C" void *memcpy(void *, const void *, unsigned long int);




extern "C" void *memmove(void *, const void *, unsigned long int);

#line 57 "/usr/include/string.h"
extern "C" void *memccpy(void *, const void *, int, unsigned long int);

#line 65 "/usr/include/string.h"
extern "C" void *memset(void *, int, unsigned long int);


extern "C" int memcmp(const void *, const void *, unsigned long int);

#line 95 "/usr/include/string.h"
extern "C" void *memchr(const void *, int, unsigned long int);

#line 128 "/usr/include/string.h"
extern "C" char *strcpy(char *, const char *);


extern "C" char *strncpy(char *, const char *, unsigned long int);




extern "C" char *strcat(char *, const char *);


extern "C" char *strncat(char *, const char *, unsigned long int);



extern "C" int strcmp(const char *, const char *);


extern "C" int strncmp(const char *, const char *, unsigned long int);



extern "C" int strcoll(const char *, const char *);


extern "C" unsigned long int strxfrm(char *, const char *, unsigned long int);

#line 175 "/usr/include/string.h"
extern "C" char *strdup(const char *);

#line 235 "/usr/include/string.h"
extern "C" char *strchr(const char *, int);

#line 262 "/usr/include/string.h"
extern "C" char *strrchr(const char *, int);

#line 284 "/usr/include/string.h"
extern "C" unsigned long int strcspn(const char *, const char *);



extern "C" unsigned long int strspn(const char *, const char *);

#line 314 "/usr/include/string.h"
extern "C" char *strpbrk(const char *, const char *);

#line 342 "/usr/include/string.h"
extern "C" char *strstr(const char *, const char *);

#line 348 "/usr/include/string.h"
extern "C" char *strtok(char *, const char *);

#line 354 "/usr/include/string.h"
extern "C" char *__strtok_r(char *, const char *, char **);




extern "C" char *strtok_r(char *, const char *, char **);

#line 399 "/usr/include/string.h"
extern "C" unsigned long int strlen(const char *);

#line 413 "/usr/include/string.h"
extern "C" char *strerror(int);

#line 431 "/usr/include/string.h"
extern "C" int __xpg_strerror_r(int, char *, unsigned long int);

#line 451 "/usr/include/string.h"
extern "C" void __bzero(void *, unsigned long int);



extern "C" void bcopy(const void *, void *, unsigned long int);



extern "C" void bzero(void *, unsigned long int);


extern "C" int bcmp(const void *, const void *, unsigned long int);

#line 489 "/usr/include/string.h"
extern "C" char *index(const char *, int);

#line 517 "/usr/include/string.h"
extern "C" char *rindex(const char *, int);

#line 523 "/usr/include/string.h"
extern "C" int ffs(int);

#line 536 "/usr/include/string.h"
extern "C" int strcasecmp(const char *, const char *);



extern "C" int strncasecmp(const char *, const char *, unsigned long int);

#line 559 "/usr/include/string.h"
extern "C" char *strsep(char **, const char *);

#line 109 "/usr/include/sys/select.h"
extern "C" int select(int, fd_set *, fd_set *, fd_set *, struct timeval *);

#line 121 "/usr/include/sys/select.h"
extern "C" int pselect(int, fd_set *, fd_set *, fd_set *, const struct timespec *, const __sigset_t *);

#line 2251 "cannyx.h"
void _scc_bit4_err_handle(const _bit4&);

//////////////////////////////////////////////////////////////////////
// End of file cannyx.h
//////////////////////////////////////////////////////////////////////
